/* Contenido de "PAES Biología" (Fabimath, beta) · Unidad 2 · Procesos y funciones biológicas · Sistema nervioso.
   Temario oficial PAES Admisión 2027, área «Procesos y funciones biológicas»: características generales del sistema
   nervioso y su función coordinadora frente a estímulos; estructura y función de la neurona; generación y propagación
   del impulso nervioso; transmisión por sinapsis química; arco reflejo simple; consecuencias del consumo de café,
   alcohol y drogas de abuso; cuidados del sistema nervioso (horas de sueño y prevención de traumatismos).
   Estilo de preguntas tomado de PAES Invierno 2026, PAES Regular 2026 y PAES Invierno 2027 (paes/biologia/fuentes/).
   Figuras TikZ en paes/biologia/tikz/ner_*.tex, compiladas a paes/biologia/fig/. Usa r (String.raw) de paes_data.js. */
const BIO_NERVIOSO = [

/* =====================================================================
   TEMA 1 · NEURONA E IMPULSO NERVIOSO
   ===================================================================== */
{
  id: 'bio_neurona', unit: 'Unidad 2 · Procesos y funciones biológicas', icon: '🧠',
  title: 'Neurona e impulso nervioso',
  desc: 'Cómo se organiza el sistema nervioso (central y periférico, somático y autónomo), cómo es una neurona y cómo genera y conduce el impulso nervioso: potencial de reposo, potencial de acción, canales de Na+ y K+, bomba Na+/K+ y conducción saltatoria.',
  slides: [
    { t: 'Cómo se organiza el sistema nervioso', b: r`
      <div class="cols"><div>
      <p>El sistema nervioso <b>coordina e integra</b> lo que hace el cuerpo frente a los <b>estímulos</b>, tanto externos (luz, sonido, calor) como internos (falta de agua, aumento de CO<sub>2</sub>). Cumple tres funciones en cadena:</p>
      <ul><li><b>Sensitiva:</b> los receptores captan el estímulo.</li>
      <li><b>Integradora:</b> el sistema nervioso central procesa la información y elabora una respuesta.</li>
      <li><b>Motora:</b> la respuesta llega a un <b>efector</b>, un músculo o una glándula.</li></ul>
      <p><b>Sistema nervioso central (SNC):</b> encéfalo (cerebro, cerebelo y tronco encefálico) y médula espinal. Está protegido por el cráneo, la columna vertebral, las meninges y el líquido cefalorraquídeo.</p>
      <p><b>Sistema nervioso periférico (SNP):</b> los nervios (12 pares craneales y 31 pares raquídeos) y los ganglios. Conecta el SNC con el resto del cuerpo.</p>
      </div><div>
      <div class="box"><b>Las divisiones del SNP</b><br>· <b>Somático:</b> controla los músculos esqueléticos; es voluntario (levantar la mano, caminar).<br>· <b>Autónomo:</b> controla el corazón, el músculo liso y las glándulas; es involuntario.<br>· <b>Simpático:</b> prepara para la acción, «lucha o huida»: aumenta la frecuencia cardíaca, dilata las pupilas y los bronquios, frena la digestión.<br>· <b>Parasimpático:</b> «reposo y digestión»: baja la frecuencia cardíaca, contrae las pupilas, estimula la salivación y los movimientos del tubo digestivo.</div>
      </div></div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/ner_organizacion.svg" alt="Esquema: el sistema nervioso se divide en central (encéfalo y médula espinal) y periférico (nervios y ganglios); el periférico se divide en somático, voluntario, y autónomo, involuntario; el autónomo se divide en simpático y parasimpático"></div>` },
    { t: 'La neurona', b: r`
      <div class="cols"><div>
      <p>La <b>neurona</b> es la célula especializada en recibir, conducir y transmitir señales. Sus partes:</p>
      <ul><li><b>Dendritas:</b> prolongaciones cortas y ramificadas que <b>reciben</b> señales de otras neuronas o de receptores.</li>
      <li><b>Soma o cuerpo celular:</b> tiene el núcleo y la mayoría de los organelos; <b>integra</b> las señales que llegan.</li>
      <li><b>Axón:</b> prolongación larga que <b>conduce</b> el impulso desde el soma hacia los terminales. Puede medir más de un metro.</li>
      <li><b>Vaina de mielina:</b> capas de membrana que envuelven el axón y lo aíslan. La forman las células de Schwann en el SNP y los oligodendrocitos en el SNC.</li>
      <li><b>Nódulos de Ranvier:</b> pequeños tramos del axón sin mielina, entre una vaina y la siguiente.</li>
      <li><b>Terminales axónicos:</b> extremos del axón que <b>liberan neurotransmisores</b> en la sinapsis.</li></ul>
      </div><div>
      <div class="box"><b>Tipos de neuronas según su función</b><br>· <b>Sensitivas o aferentes:</b> llevan información desde los receptores al SNC.<br>· <b>Interneuronas:</b> están dentro del SNC y conectan neuronas entre sí.<br>· <b>Motoras o eferentes:</b> llevan la orden desde el SNC a los efectores.</div>
      <div class="box"><b>Recuerda</b> En una neurona el impulso viaja en un sentido: dendritas → soma → axón → terminales axónicos. Las neuronas tienen muchas mitocondrias porque gastan mucho ATP, sobre todo en la bomba Na<sup>+</sup>/K<sup>+</sup>.</div>
      </div></div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/ner_neurona.svg" alt="Neurona con dendritas, soma con núcleo, axón cubierto por vainas de mielina separadas por nódulos de Ranvier y terminales axónicos; una flecha indica que el impulso va del soma hacia los terminales"></div>` },
    { t: 'Potencial de reposo', b: r`
      <div class="cols"><div>
      <p>Una neurona en reposo tiene una diferencia de carga entre los dos lados de su membrana: el interior es <b>negativo</b> respecto del exterior. Esa diferencia, cercana a <b>−70 mV</b>, es el <b>potencial de reposo</b>. Se dice que la membrana está <b>polarizada</b>.</p>
      <p>¿De dónde sale? De dos hechos:</p>
      <ul><li><b>Distinta concentración de iones.</b> Afuera hay mucho Na<sup>+</sup>; adentro hay mucho K<sup>+</sup>. La <b>bomba Na<sup>+</sup>/K<sup>+</sup></b> mantiene estas diferencias: saca 3 Na<sup>+</sup> y mete 2 K<sup>+</sup> en cada ciclo, gastando ATP (es transporte activo).</li>
      <li><b>Distinta permeabilidad.</b> En reposo, la membrana tiene abiertos algunos <b>canales de K<sup>+</sup></b> y casi ningún canal de Na<sup>+</sup>. El K<sup>+</sup> sale a favor de su gradiente y deja el interior con carga negativa.</li></ul>
      </div><div>
      <div class="box"><b>Ejemplo resuelto</b> Si se bloquea la producción de ATP de una neurona, ¿qué le pasa al potencial de reposo? La bomba Na<sup>+</sup>/K<sup>+</sup> se detiene. Los iones siguen moviéndose por sus canales, así que de a poco entra Na<sup>+</sup>, sale K<sup>+</sup> y las concentraciones se igualan: el potencial de reposo se vuelve <b>menos negativo</b> y, con el tiempo, la neurona deja de responder.</div>
      </div></div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/ner_membrana.svg" alt="Membrana de una neurona en reposo: afuera hay mucho Na+ y cargas positivas; adentro hay mucho K+ y cargas negativas; un canal de K+ abierto deja salir K+, un canal de Na+ está cerrado y la bomba Na+/K+ saca 3 Na+ y mete 2 K+ gastando ATP; potencial de reposo de −70 mV"></div>` },
    { t: 'Potencial de acción', b: r`
      <div class="cols"><div>
      <p>Cuando un estímulo despolariza la membrana hasta el <b>umbral</b> (cerca de −55 mV), se produce un <b>potencial de acción</b>: un cambio rápido del potencial que dura unos 2 ms. Tiene tres fases:</p>
      <ul><li><b>Despolarización.</b> Se abren los canales de Na<sup>+</sup> dependientes de voltaje y el Na<sup>+</sup> <b>entra</b> en masa. El interior se vuelve positivo, hasta unos +30 a +40 mV.</li>
      <li><b>Repolarización.</b> Los canales de Na<sup>+</sup> se cierran (se inactivan) y se abren los canales de K<sup>+</sup> dependientes de voltaje. El K<sup>+</sup> <b>sale</b> y el interior vuelve a ser negativo.</li>
      <li><b>Hiperpolarización.</b> Los canales de K<sup>+</sup> tardan en cerrarse, sale un poco más de K<sup>+</sup> y el potencial baja de −70 mV por un momento (cerca de −80 mV). Luego vuelve al reposo.</li></ul>
      </div><div>
      <div class="box"><b>Recuerda</b> Durante el potencial de acción se mueven muy pocos iones comparados con los que hay en la célula: las concentraciones casi no cambian. La bomba Na<sup>+</sup>/K<sup>+</sup> trabaja todo el tiempo para mantenerlas, pero no es la que produce la despolarización ni la repolarización: eso lo hacen los canales.</div>
      </div></div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/ner_potencial.svg" alt="Gráfico del potencial de membrana en el tiempo: en reposo está en −70 mV; tras el estímulo sube hasta el umbral de −55 mV, luego sube rápido hasta +35 mV (despolarización, entra Na+), baja rápido (repolarización, sale K+), cae hasta −80 mV (hiperpolarización) y vuelve a −70 mV"></div>` },
    { t: 'Umbral y ley del todo o nada', b: r`
      <div class="cols"><div>
      <p>Un estímulo débil abre pocos canales: el potencial sube un poco y vuelve al reposo sin generar impulso. Si el estímulo alcanza el <b>umbral</b>, se dispara un potencial de acción <b>completo</b>.</p>
      <p>Esto es la <b>ley del todo o nada</b>: si se alcanza el umbral, el potencial de acción siempre tiene la misma amplitud; si no se alcanza, no hay potencial de acción.</p>
      <p>Entonces, ¿cómo distingue el cerebro un pinchazo leve de uno fuerte? Por la <b>frecuencia</b>: un estímulo más intenso genera <b>más potenciales de acción por segundo</b>, no potenciales más grandes. También activa más neuronas a la vez.</p>
      </div><div>
      <div class="box"><b>Período refractario</b> Justo después de un potencial de acción, los canales de Na<sup>+</sup> quedan inactivados por un instante y la membrana no puede disparar otro impulso, aunque llegue un estímulo fuerte. Por eso el impulso no puede devolverse por el tramo que acaba de pasar y viaja en un solo sentido.</div>
      </div></div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/ner_todo_nada.svg" alt="Gráfico con tres estímulos: E1, débil, solo sube un poco el potencial sin llegar al umbral; E2, medio, y E3, intenso, superan el umbral y producen potenciales de acción de igual altura, hasta +35 mV"></div>` },
    { t: 'Propagación y conducción saltatoria', b: r`
      <div class="cols"><div>
      <p>El potencial de acción que se genera al inicio del axón despolariza el tramo vecino hasta el umbral. Ese tramo dispara su propio potencial de acción, que despolariza al siguiente, y así hasta los terminales. El impulso <b>se regenera</b> en cada punto, por eso llega con la misma amplitud al final del axón.</p>
      <p><b>Axón sin mielina:</b> el impulso recorre toda la membrana, punto a punto. Es una conducción <b>continua</b> y lenta (0,5 a 2 m/s).</p>
      <p><b>Axón con mielina:</b> la mielina aísla la membrana y los canales de Na<sup>+</sup> se concentran en los nódulos de Ranvier. El potencial de acción solo se genera en los nódulos y «salta» de uno al siguiente: es la <b>conducción saltatoria</b>, mucho más rápida (hasta 120 m/s) y con menos gasto de energía.</p>
      </div><div>
      <div class="box"><b>Qué hace más rápida la conducción</b><br>· La <b>mielina</b>: es el factor más importante en los vertebrados.<br>· El <b>diámetro</b> del axón: a mayor diámetro, mayor velocidad. El calamar tiene axones gigantes sin mielina, de hasta 1 mm de grosor.</div>
      <div class="box"><b>Aplicación: esclerosis múltiple</b> El sistema inmune daña la mielina del SNC. Los impulsos se vuelven lentos o se bloquean, y aparecen problemas de visión, de movimiento y de sensibilidad.</div>
      </div></div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/ner_saltatoria.svg" alt="Arriba, axón sin mielina con flechas pequeñas seguidas: conducción continua y lenta. Abajo, axón con vainas de mielina y flechas curvas que saltan de un nódulo de Ranvier al siguiente: conducción saltatoria y rápida"></div>` },
    { t: 'Lo clave del tema', b: r`
      <table><thead><tr><th>Momento</th><th>Qué canales están abiertos</th><th>Movimiento de iones</th><th>Potencial</th></tr></thead><tbody>
      <tr><td>Reposo</td><td>algunos de K<sup>+</sup> (de fuga)</td><td>sale algo de K<sup>+</sup>; la bomba saca 3 Na<sup>+</sup> y mete 2 K<sup>+</sup></td><td>−70 mV</td></tr>
      <tr><td>Despolarización</td><td>de Na<sup>+</sup> dependientes de voltaje</td><td>entra Na<sup>+</sup></td><td>sube hasta +30 a +40 mV</td></tr>
      <tr><td>Repolarización</td><td>de K<sup>+</sup> dependientes de voltaje</td><td>sale K<sup>+</sup></td><td>baja hacia valores negativos</td></tr>
      <tr><td>Hiperpolarización</td><td>de K<sup>+</sup>, que tardan en cerrarse</td><td>sigue saliendo K<sup>+</sup></td><td>cerca de −80 mV</td></tr></tbody></table>
      <div class="box" style="margin-top:14px"><b>Recuerda</b><br>· Dendritas reciben, soma integra, axón conduce, terminales liberan neurotransmisores.<br>· El simpático activa («lucha o huida»); el parasimpático favorece el reposo y la digestión.<br>· La bomba Na<sup>+</sup>/K<sup>+</sup> gasta ATP y mantiene los gradientes; los canales producen el potencial de acción.<br>· Todo o nada: la intensidad del estímulo se codifica en la frecuencia de impulsos.<br>· La mielina permite la conducción saltatoria, de nódulo en nódulo.</div>
      <div class="box" style="margin-top:14px"><b>Método PAES</b> 1. En un gráfico de potencial, ubica primero el reposo (−70 mV) y el umbral. 2. Si sube: entra Na<sup>+</sup>; si baja: sale K<sup>+</sup>. 3. Si un fármaco bloquea algo, pregúntate qué fase depende de eso y qué se ve alterado en el gráfico. 4. En una tabla de velocidades, compara de a dos los axones que se diferencian en una sola variable (mielina o diámetro).</div>` }
  ],
  example: {
    src: 'Estilo PAES',
    enun: r`<p>El siguiente gráfico muestra el registro del potencial de membrana de un axón antes, durante y después de un potencial de acción. Los números indican cuatro tramos de la curva.</p><p>¿En qué tramo se abren los canales de Na<sup>+</sup> dependientes de voltaje y el Na<sup>+</sup> entra a la neurona?</p>`,
    fig: { type: 'img', src: 'paes/biologia/fig/ner_potencial_num.svg', alt: 'Gráfico de potencial de membrana en el tiempo: tramo 1, reposo en −70 mV; tramo 2, subida rápida desde el umbral de −55 mV hasta +35 mV; tramo 3, bajada rápida; tramo 4, descenso hasta −80 mV, bajo el nivel de reposo' },
    alts: ['Tramo 1', 'Tramo 2', 'Tramo 3', 'Tramo 4'], ok: 1,
    sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El tramo en que entra Na<sup>+</sup>. Como el Na<sup>+</sup> tiene carga positiva y entra, el interior se vuelve <b>menos negativo</b>: el potencial debe <b>subir</b>.</p><p><b>Paso 2. Lee el gráfico.</b> En el tramo 1 el potencial está estable en −70 mV: es el reposo. En el tramo 2 sube rápidamente desde el umbral hasta valores positivos: es la <b>despolarización</b>. En el tramo 3 baja y en el tramo 4 queda por debajo de −70 mV.</p><p><b>Paso 3. Une ambas ideas.</b> La subida rápida se debe a la apertura de los canales de Na<sup>+</sup> dependientes de voltaje y a la entrada de Na<sup>+</sup>.</p><p><b>Respuesta:</b> tramo 2.</p><p><b>¿Por qué no las otras?</b> En el tramo 1 la membrana está en reposo y los canales de Na<sup>+</sup> dependientes de voltaje están cerrados. En el tramo 3 (repolarización) los canales de Na<sup>+</sup> se inactivan y sale K<sup>+</sup>. En el tramo 4 (hiperpolarización) sigue saliendo K<sup>+</sup> porque sus canales tardan en cerrarse.</p>`,
    conc: 'Si el potencial sube, entra Na+ (despolarización); si baja, sale K+ (repolarización).'
  },
  bank: [
    /* Tipo 1: organización del sistema nervioso y divisiones del autónomo */
    { enun: r`<p>Una persona camina de noche por una calle oscura y escucha un ruido fuerte detrás de ella. En pocos segundos su corazón late más rápido, sus pupilas se dilatan y su respiración se acelera. Estas respuestas son involuntarias.</p><p>¿Qué parte del sistema nervioso produce principalmente estas respuestas?</p>`, src: 'Estilo PAES',
      alts: ['La división simpática del sistema nervioso autónomo.', 'La división parasimpática del sistema nervioso autónomo.', 'El sistema nervioso somático.', 'El cerebelo, que coordina el equilibrio.'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> La división que controla respuestas <b>involuntarias</b> que preparan al cuerpo frente a un peligro.</p><p><b>Paso 2. Involuntario → autónomo.</b> El corazón, el músculo de la pupila y los bronquios no se controlan a voluntad: los regula el sistema nervioso autónomo.</p><p><b>Paso 3. ¿Cuál de sus divisiones?</b> Aumentar la frecuencia cardíaca, dilatar las pupilas y acelerar la respiración son respuestas de «lucha o huida»: las produce la división <b>simpática</b>.</p><p><b>Respuesta:</b> la división simpática del sistema nervioso autónomo.</p><p><b>¿Por qué no las otras?</b> La división parasimpática hace lo contrario: baja la frecuencia cardíaca y contrae las pupilas. El sistema somático controla los músculos esqueléticos de forma voluntaria. El cerebelo coordina el equilibrio y los movimientos, no el ritmo cardíaco ni las pupilas.</p>`, conc: 'Respuestas involuntarias de alerta («lucha o huida») = simpático.' },
    { enun: r`<p>Un estudiante escribe tres afirmaciones sobre la organización del sistema nervioso humano:</p><p>I) La médula espinal forma parte del sistema nervioso central.<br>II) Los nervios que llevan información desde la piel hasta la médula espinal forman parte del sistema nervioso periférico.<br>III) El sistema nervioso autónomo controla la contracción voluntaria de los músculos esqueléticos.</p><p>¿Cuál(es) de ellas es (son) correcta(s)?</p>`, src: 'Estilo PAES',
      alts: ['Solo I', 'Solo II', 'Solo I y II', 'I, II y III'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Revisar cada afirmación con la organización del sistema nervioso.</p><p><b>Paso 2. Afirmación I.</b> El sistema nervioso central está formado por el encéfalo y la <b>médula espinal</b>. <b>Correcta.</b></p><p><b>Paso 3. Afirmación II.</b> Los nervios, tanto los que llevan información hacia el SNC como los que salen de él, forman el sistema nervioso periférico. <b>Correcta.</b></p><p><b>Paso 4. Afirmación III.</b> Los músculos esqueléticos y los movimientos voluntarios los controla el sistema <b>somático</b>. El autónomo controla el corazón, el músculo liso y las glándulas, de forma involuntaria. <b>Incorrecta.</b></p><p><b>Respuesta:</b> solo I y II.</p><p><b>¿Por qué no las otras?</b> «Solo I» y «Solo II» dejan fuera una afirmación correcta. «I, II y III» incluye la III, que asigna al autónomo una función del somático.</p>`, conc: 'SNC = encéfalo y médula; SNP = nervios y ganglios; somático = voluntario.' },
    { enun: r`<p>Después de almorzar, una persona se recuesta a descansar. En ese momento predomina la acción de la división parasimpática de su sistema nervioso autónomo.</p><p>¿Cuál de las siguientes respuestas es esperable en esta situación?</p>`, src: 'Estilo PAES',
      alts: ['Aumento de la frecuencia cardíaca.', 'Dilatación de las pupilas.', 'Disminución de la secreción de saliva y de jugos digestivos.', 'Aumento de los movimientos del tubo digestivo.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Un efecto de la división parasimpática, la de «reposo y digestión».</p><p><b>Paso 2. Recuerda su función.</b> El parasimpático favorece las funciones de mantención del cuerpo en reposo: baja la frecuencia cardíaca, contrae las pupilas y <b>estimula la digestión</b> (más saliva, más jugos digestivos y más movimientos del tubo digestivo).</p><p><b>Respuesta:</b> aumento de los movimientos del tubo digestivo.</p><p><b>¿Por qué no las otras?</b> Aumentar la frecuencia cardíaca y dilatar las pupilas son efectos del simpático. Disminuir la saliva y los jugos digestivos también es propio del simpático, que frena la digestión en una situación de alerta.</p>`, conc: 'Parasimpático = reposo y digestión: estimula el tubo digestivo y baja la frecuencia cardíaca.' },

    /* Tipo 2: estructura y función de la neurona (Invierno 2026 n.º 59, Invierno 2027 n.º 57) */
    { enun: r`<p>El siguiente esquema representa una neurona motora. Los números indican algunas de sus estructuras.</p><p>¿Qué estructura recibe principalmente las señales de otras neuronas y cuál libera neurotransmisores, respectivamente?</p>`, src: 'PAES Invierno 2026, adaptada',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_neurona_num.svg', alt: 'Neurona con cinco estructuras numeradas: 1, prolongaciones cortas y ramificadas que salen del cuerpo celular; 2, cuerpo celular con núcleo; 3, envoltura que cubre tramos del axón; 4, espacio sin envoltura entre dos tramos cubiertos del axón; 5, extremos ramificados al final del axón' },
      alts: ['1 y 3', '1 y 5', '2 y 4', '3 y 5'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Dos estructuras: la que recibe señales y la que libera neurotransmisores.</p><p><b>Paso 2. Identifica cada número.</b> 1: dendritas. 2: soma o cuerpo celular. 3: vaina de mielina. 4: nódulo de Ranvier. 5: terminales axónicos.</p><p><b>Paso 3. Asigna funciones.</b> Las <b>dendritas</b> (1) reciben las señales de otras neuronas. Los <b>terminales axónicos</b> (5) tienen las vesículas con neurotransmisores y los liberan en la sinapsis.</p><p><b>Respuesta:</b> 1 y 5.</p><p><b>¿Por qué no las otras?</b> La estructura 3 es la mielina: aísla el axón y acelera la conducción, pero no libera neurotransmisores. El 2 (soma) integra las señales y el 4 (nódulo de Ranvier) es donde se regenera el impulso; ninguno de los dos es la zona de liberación.</p>`, conc: 'Dendritas reciben; terminales axónicos liberan neurotransmisores.' },
    { enun: r`<p>En la esclerosis múltiple, el sistema inmune de la persona daña la estructura indicada con el número 3 en los axones del sistema nervioso central.</p><p>¿Qué efecto directo tiene este daño sobre la función de esas neuronas?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_neurona_num.svg', alt: 'Neurona con cinco estructuras numeradas: 1, prolongaciones cortas y ramificadas que salen del cuerpo celular; 2, cuerpo celular con núcleo; 3, envoltura que cubre tramos del axón; 4, espacio sin envoltura entre dos tramos cubiertos del axón; 5, extremos ramificados al final del axón' },
      alts: ['Las dendritas dejan de recibir señales de otras neuronas.', 'El soma deja de fabricar neurotransmisores.', 'La conducción del impulso por el axón se vuelve más lenta o se bloquea.', 'El impulso comienza a viajar desde los terminales axónicos hacia el soma.'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El efecto de dañar la estructura 3.</p><p><b>Paso 2. Identifícala.</b> La estructura 3 es la <b>vaina de mielina</b>. Aísla el axón y permite la conducción saltatoria, de un nódulo de Ranvier al siguiente.</p><p><b>Paso 3. Deduce el efecto.</b> Sin mielina, el impulso ya no salta entre nódulos: avanza mucho más lento o, si el daño es grande, se pierde en el camino.</p><p><b>Respuesta:</b> la conducción del impulso por el axón se vuelve más lenta o se bloquea.</p><p><b>¿Por qué no las otras?</b> Las dendritas no tienen mielina y siguen recibiendo señales. La síntesis de neurotransmisores depende del soma y de los terminales, no de la mielina. El sentido del impulso no se invierte: lo determinan el período refractario y la sinapsis, no la mielina.</p>`, conc: 'Sin mielina no hay conducción saltatoria: el impulso se hace lento o se bloquea.' },
    { enun: r`<p>A fines del siglo XIX, Santiago Ramón y Cajal propuso que el tejido nervioso está formado por neuronas independientes, que se comunican sin que sus citoplasmas estén unidos. Otros científicos sostenían que el tejido nervioso era una red continua de citoplasma.</p><p>Hoy se trabaja con un cultivo de neuronas que se comunican mediante sinapsis químicas. ¿Cuál de los siguientes resultados apoya la propuesta de Ramón y Cajal?</p>`, src: 'PAES Invierno 2027, adaptada',
      alts: ['Un colorante inyectado en el soma de una neurona llena sus dendritas y su axón, pero no aparece en las neuronas con las que hace sinapsis.', 'Un colorante inyectado en el soma de una neurona aparece después en el citoplasma de las neuronas vecinas.', 'Un colorante agregado al medio de cultivo no entra a ninguna de las neuronas.', 'Al microscopio óptico, las prolongaciones de neuronas vecinas se ven en contacto.'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Una evidencia de que cada neurona es una célula independiente, con su propio citoplasma.</p><p><b>Paso 2. Piensa qué esperarías.</b> Si cada neurona es independiente, una sustancia dentro de una neurona debe recorrer <b>toda esa neurona</b> (dendritas, soma y axón) pero <b>no pasar</b> a la siguiente, porque las separa la membrana y el espacio sináptico.</p><p><b>Respuesta:</b> el colorante llena la neurona inyectada pero no aparece en las neuronas con las que hace sinapsis.</p><p><b>¿Por qué no las otras?</b> Que el colorante pase a las neuronas vecinas apoyaría la idea de una red continua. Que un colorante del medio no entre a las neuronas solo muestra que la membrana es selectiva, no dice si las neuronas están unidas entre sí. Al microscopio óptico no se distingue si las prolongaciones se tocan o están separadas por un espacio muy pequeño, así que esa observación no decide el debate.</p>`, conc: 'Si una sustancia llena una neurona y no pasa a la siguiente, las neuronas son células independientes.' },

    /* Tipo 3: potencial de reposo y bomba Na+/K+ (Invierno 2027 n.º 58) */
    { enun: r`<p>El esquema representa la membrana de una neurona en reposo, con la distribución de algunos iones y tres proteínas de membrana.</p><p>¿Cuál de las siguientes afirmaciones es correcta?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_membrana.svg', alt: 'Membrana de una neurona en reposo: afuera hay mucho Na+ y cargas positivas; adentro hay mucho K+ y cargas negativas; un canal de K+ abierto deja salir K+, un canal de Na+ está cerrado y la bomba Na+/K+ saca 3 Na+ y mete 2 K+ gastando ATP; potencial de reposo de −70 mV' },
      alts: ['El interior de la neurona es positivo respecto del exterior.', 'La concentración de Na<sup>+</sup> es mayor dentro de la neurona que fuera de ella.', 'La bomba Na<sup>+</sup>/K<sup>+</sup> mete 3 Na<sup>+</sup> y saca 2 K<sup>+</sup> sin gastar energía.', 'La bomba Na<sup>+</sup>/K<sup>+</sup> saca 3 Na<sup>+</sup> y mete 2 K<sup>+</sup> usando ATP.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Una afirmación correcta sobre la neurona en reposo, leyendo el esquema.</p><p><b>Paso 2. Lee el esquema.</b> Afuera hay muchos Na<sup>+</sup> y cargas positivas; adentro, muchos K<sup>+</sup> y cargas negativas. La bomba saca 3 Na<sup>+</sup> (flecha hacia afuera) y mete 2 K<sup>+</sup> (flecha hacia adentro), y dice «gasta ATP».</p><p><b>Paso 3. Razona.</b> La bomba mueve los iones <b>contra</b> su gradiente: el Na<sup>+</sup> sale hacia donde ya hay mucho Na<sup>+</sup>, y el K<sup>+</sup> entra hacia donde ya hay mucho K<sup>+</sup>. Por eso necesita energía: es transporte activo.</p><p><b>Respuesta:</b> la bomba Na<sup>+</sup>/K<sup>+</sup> saca 3 Na<sup>+</sup> y mete 2 K<sup>+</sup> usando ATP.</p><p><b>¿Por qué no las otras?</b> En reposo el interior es negativo (−70 mV). El Na<sup>+</sup> está más concentrado afuera. La tercera opción invierte el sentido de la bomba y olvida que gasta ATP.</p>`, conc: 'La bomba Na+/K+ saca 3 Na+ y mete 2 K+ contra gradiente, gastando ATP.' },
    { enun: r`<p>La ouabaína es una sustancia de origen vegetal que inhibe la bomba Na<sup>+</sup>/K<sup>+</sup>. Un grupo de investigación agrega ouabaína a un cultivo de neuronas y las observa durante varias horas, sin estimularlas.</p><p>¿Qué resultado es esperable?</p>`, src: 'Estilo PAES',
      alts: ['Las diferencias de concentración de Na<sup>+</sup> y K<sup>+</sup> entre el interior y el exterior aumentan con el tiempo.', 'Poco a poco el Na<sup>+</sup> se acumula dentro de la neurona, el K<sup>+</sup> interno disminuye y el potencial de reposo se vuelve menos negativo.', 'El interior de la neurona se vuelve positivo de inmediato y se mantiene así, como en un potencial de acción permanente.', 'Las neuronas pierden sus canales de K<sup>+</sup> y el potencial de membrana queda en −70 mV.'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Predecir qué pasa cuando la bomba Na<sup>+</sup>/K<sup>+</sup> deja de funcionar.</p><p><b>Paso 2. ¿Qué hace la bomba?</b> Saca Na<sup>+</sup> y mete K<sup>+</sup> continuamente, compensando los iones que se filtran por los canales. Así mantiene las diferencias de concentración.</p><p><b>Paso 3. Sin bomba.</b> Los iones siguen moviéndose a favor de su gradiente: el Na<sup>+</sup> entra y el K<sup>+</sup> sale, pero nadie los devuelve. Las concentraciones se van igualando de a poco y el interior pierde su carga negativa: el potencial de reposo se acerca a 0 mV.</p><p><b>Respuesta:</b> el Na<sup>+</sup> se acumula dentro, el K<sup>+</sup> interno disminuye y el potencial de reposo se vuelve menos negativo.</p><p><b>¿Por qué no las otras?</b> Los gradientes no pueden aumentar si se detiene lo que los mantiene. El cambio es gradual, en horas, no inmediato como un potencial de acción. La ouabaína actúa sobre la bomba, no elimina los canales de K<sup>+</sup>, y sin bomba el potencial no se queda en −70 mV.</p>`, conc: 'Sin bomba Na+/K+, los gradientes se disipan y el potencial de reposo se vuelve menos negativo.' },
    { enun: r`<p>Un equipo de investigación quiere comprobar que un nuevo compuesto, llamado Z, inhibe la bomba Na<sup>+</sup>/K<sup>+</sup> de las neuronas. Para ello, prepara cultivos de neuronas con Z y sin Z.</p><p>¿Qué variable deberían medir en ambos cultivos para comprobar el efecto de Z?</p>`, src: 'PAES Invierno 2027, adaptada',
      alts: ['La concentración de Na<sup>+</sup> dentro de las neuronas a lo largo del tiempo.', 'La cantidad de neurotransmisor almacenada en las vesículas sinápticas.', 'El grosor de la vaina de mielina de los axones.', 'El número de dendritas de cada neurona.'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Una variable que cambie directamente si la bomba Na<sup>+</sup>/K<sup>+</sup> deja de funcionar.</p><p><b>Paso 2. ¿Qué hace la bomba?</b> Saca Na<sup>+</sup> de la célula y mete K<sup>+</sup>. Si Z la inhibe, el Na<sup>+</sup> que se filtra hacia adentro ya no sale: la concentración de Na<sup>+</sup> interna <b>debería subir</b> en el cultivo con Z y mantenerse estable en el cultivo sin Z.</p><p><b>Respuesta:</b> la concentración de Na<sup>+</sup> dentro de las neuronas a lo largo del tiempo.</p><p><b>¿Por qué no las otras?</b> El neurotransmisor almacenado, el grosor de la mielina y el número de dendritas no dependen directamente del funcionamiento de la bomba; aunque cambiaran, no permitirían atribuir el cambio a la bomba.</p>`, conc: 'Para probar un efecto, mide la variable que depende directamente del mecanismo estudiado.' },

    /* Tipo 4: lectura de gráficos de potencial de membrana (Invierno 2026 n.º 5) */
    { enun: r`<p>El gráfico muestra el registro del potencial de membrana de un axón. Los números indican cuatro tramos de la curva.</p><p>¿Qué afirmación sobre el tramo 4 es correcta?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_potencial_num.svg', alt: 'Gráfico de potencial de membrana en el tiempo: tramo 1, reposo en −70 mV; tramo 2, subida rápida desde el umbral de −55 mV hasta +35 mV; tramo 3, bajada rápida; tramo 4, descenso hasta −80 mV, bajo el nivel de reposo' },
      alts: ['Se abren canales de Na<sup>+</sup> y entra Na<sup>+</sup> a la neurona.', 'La neurona está en reposo y no hay movimiento de iones a través de la membrana.', 'El potencial supera el umbral y se dispara un nuevo potencial de acción.', 'El potencial queda más negativo que el de reposo porque el K<sup>+</sup> sigue saliendo por canales que tardan en cerrarse.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Explicar el tramo 4.</p><p><b>Paso 2. Lee el gráfico.</b> En el tramo 4 el potencial baja hasta unos −80 mV, por debajo del reposo (−70 mV): es la <b>hiperpolarización</b>.</p><p><b>Paso 3. Explica.</b> Durante la repolarización se abrieron los canales de K<sup>+</sup> dependientes de voltaje. Estos canales se cierran lentamente, así que sale un poco más de K<sup>+</sup> del necesario y el interior queda más negativo por un momento.</p><p><b>Respuesta:</b> el potencial queda más negativo que el de reposo porque el K<sup>+</sup> sigue saliendo.</p><p><b>¿Por qué no las otras?</b> La entrada de Na<sup>+</sup> hace subir el potencial (tramo 2), no bajarlo. En el tramo 4 la membrana no está en reposo: el potencial está cambiando y hay salida de K<sup>+</sup>. El potencial está lejos del umbral (−55 mV), así que no se dispara otro potencial de acción.</p>`, conc: 'Hiperpolarización: el K+ sigue saliendo y el potencial baja de −70 mV.' },
    { enun: r`<p>Un grupo de investigación estimula un axón y registra su potencial de membrana en tres condiciones: sin tratamiento (control), con la sustancia P y con la sustancia Q. La flecha azul indica el momento del estímulo, que es igual en los tres casos.</p><p>¿Qué mecanismo de acción explica los resultados?</p>`, src: 'PAES Invierno 2026, adaptada',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_efectos.svg', alt: 'Tres gráficos de potencial de membrana. Control: potencial de acción normal que sube a +35 mV y vuelve a −70 mV en unos 2 ms. Con sustancia P: el potencial solo sube un poco, sin llegar al umbral de −55 mV, y vuelve a −70 mV. Con sustancia Q: el potencial sube a +35 mV igual que en el control, pero baja muy lentamente y tarda unos 5 ms en volver a −70 mV' },
      alts: ['P bloquea los canales de K<sup>+</sup> dependientes de voltaje y Q bloquea los canales de Na<sup>+</sup> dependientes de voltaje.', 'P activa la bomba Na<sup>+</sup>/K<sup>+</sup> y Q la inhibe.', 'P bloquea los canales de Na<sup>+</sup> dependientes de voltaje y Q bloquea los canales de K<sup>+</sup> dependientes de voltaje.', 'P y Q bloquean los canales de Na<sup>+</sup> dependientes de voltaje.'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Qué bloquea cada sustancia, comparando cada gráfico con el control.</p><p><b>Paso 2. Sustancia P.</b> No hay despolarización: el potencial nunca sube hasta valores positivos. La fase que falta depende de la <b>entrada de Na<sup>+</sup></b>, así que P bloquea los canales de Na<sup>+</sup> dependientes de voltaje. Así actúa la tetrodotoxina, el veneno del pez globo.</p><p><b>Paso 3. Sustancia Q.</b> La subida es normal, pero la bajada es muy lenta y no hay hiperpolarización. La repolarización depende de la <b>salida de K<sup>+</sup></b>, así que Q bloquea los canales de K<sup>+</sup> dependientes de voltaje.</p><p><b>Respuesta:</b> P bloquea los canales de Na<sup>+</sup> y Q bloquea los canales de K<sup>+</sup>.</p><p><b>¿Por qué no las otras?</b> La primera opción invierte los efectos. La bomba Na<sup>+</sup>/K<sup>+</sup> no genera las fases del potencial de acción: actúa de fondo, manteniendo los gradientes. Si Q bloqueara los canales de Na<sup>+</sup>, el potencial no habría subido.</p>`, conc: 'Sin subida: falló la entrada de Na+. Bajada lenta: falló la salida de K+.' },
    { enun: r`<p>Un axón recibe tres estímulos eléctricos de distinta intensidad (E1, E2 y E3), separados en el tiempo. El gráfico muestra el potencial de membrana registrado.</p><p>¿Qué conclusión es correcta según estos resultados?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_todo_nada.svg', alt: 'Gráfico con tres estímulos: E1, débil, solo sube un poco el potencial sin llegar al umbral; E2, medio, y E3, intenso, superan el umbral y producen potenciales de acción de igual altura, hasta +35 mV' },
      alts: ['A mayor intensidad del estímulo, mayor es la amplitud del potencial de acción.', 'E2 y E3 superan el umbral y generan potenciales de acción de igual amplitud.', 'E1 genera un potencial de acción más pequeño que los demás.', 'El valor del umbral cambia según la intensidad del estímulo.'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Una conclusión que se apoye en el gráfico.</p><p><b>Paso 2. Lee cada estímulo.</b> E1 solo produce una pequeña subida que no alcanza el umbral (−55 mV): no hay potencial de acción. E2 y E3 superan el umbral y producen potenciales de acción que llegan al mismo valor, unos +35 mV.</p><p><b>Paso 3. Interpreta.</b> Es la <b>ley del todo o nada</b>: alcanzado el umbral, el potencial de acción es siempre igual, sin importar cuánto más fuerte sea el estímulo.</p><p><b>Respuesta:</b> E2 y E3 superan el umbral y generan potenciales de acción de igual amplitud.</p><p><b>¿Por qué no las otras?</b> E3 es más intenso que E2 y su potencial de acción es igual de alto: la amplitud no depende de la intensidad. La respuesta a E1 no es un potencial de acción, porque no alcanza el umbral. El umbral está en −55 mV en los tres casos.</p>`, conc: 'Todo o nada: superado el umbral, el potencial de acción siempre tiene la misma amplitud.' },

    /* Tipo 5: propagación y conducción saltatoria */
    { enun: r`<p>La tabla muestra la velocidad de conducción del impulso en cuatro axones distintos:</p><table><thead><tr><th>Axón</th><th>Mielina</th><th>Diámetro (µm)</th><th>Velocidad (m/s)</th></tr></thead><tbody><tr><td>P (humano)</td><td>sí</td><td>12</td><td>70</td></tr><tr><td>Q (humano)</td><td>sí</td><td>4</td><td>24</td></tr><tr><td>R (humano)</td><td>no</td><td>1</td><td>1</td></tr><tr><td>S (calamar)</td><td>no</td><td>500</td><td>25</td></tr></tbody></table><p>¿Qué conclusión es correcta según estos datos?</p>`, src: 'Estilo PAES',
      alts: ['La velocidad de conducción depende solo del diámetro del axón.', 'La mielina disminuye la velocidad de conducción.', 'Todos los axones sin mielina conducen más lento que todos los axones con mielina.', 'Un axón con mielina delgado puede conducir tan rápido como un axón sin mielina mucho más grueso.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Una conclusión que se cumpla con todos los datos de la tabla.</p><p><b>Paso 2. Compara de a dos.</b> P y Q tienen mielina y distinto diámetro: el más grueso (P) es más rápido. Q y S tienen velocidades casi iguales (24 y 25 m/s), pero Q mide 4 µm con mielina y S mide 500 µm sin mielina: S es 125 veces más grueso.</p><p><b>Respuesta:</b> un axón con mielina delgado puede conducir tan rápido como un axón sin mielina mucho más grueso.</p><p><b>¿Por qué no las otras?</b> Si dependiera solo del diámetro, S sería el más rápido de todos, y no lo es. La mielina aumenta la velocidad: los axones con mielina son rápidos aun siendo delgados. S (sin mielina) conduce a 25 m/s, más que Q (con mielina, 24 m/s), así que no todos los axones sin mielina son más lentos.</p>`, conc: 'La mielina permite conducción rápida con axones delgados; sin ella, se necesita un diámetro enorme.' },
    { enun: r`<p>En los axones con mielina, el potencial de acción se genera solo en los nódulos de Ranvier y avanza «saltando» de un nódulo al siguiente, como muestra el esquema.</p><p>¿Qué explica que el potencial de acción se genere solo en los nódulos?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_saltatoria.svg', alt: 'Arriba, axón sin mielina con flechas pequeñas seguidas: conducción continua y lenta. Abajo, axón con vainas de mielina y flechas curvas que saltan de un nódulo de Ranvier al siguiente: conducción saltatoria y rápida' },
      alts: ['La mielina aísla la membrana del axón y los canales de Na<sup>+</sup> dependientes de voltaje se concentran en los nódulos.', 'En los nódulos de Ranvier el axón no tiene membrana plasmática.', 'La mielina fabrica los neurotransmisores que despolarizan los nódulos.', 'En los nódulos de Ranvier se ubican las vesículas sinápticas.'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Por qué el potencial de acción aparece solo en los nódulos.</p><p><b>Paso 2. ¿Qué se necesita para un potencial de acción?</b> Que la membrana tenga contacto con el líquido extracelular y canales de Na<sup>+</sup> dependientes de voltaje que se abran y dejen entrar Na<sup>+</sup>.</p><p><b>Paso 3. Aplica.</b> Bajo la mielina la membrana está aislada y casi no hay intercambio de iones. En los nódulos, en cambio, la membrana queda expuesta y tiene muchísimos canales de Na<sup>+</sup>. Por eso el impulso se regenera solo ahí.</p><p><b>Respuesta:</b> la mielina aísla la membrana y los canales de Na<sup>+</sup> se concentran en los nódulos.</p><p><b>¿Por qué no las otras?</b> En los nódulos sí hay membrana plasmática: justamente ahí está expuesta. La mielina no fabrica neurotransmisores, y el impulso dentro del axón es eléctrico. Las vesículas sinápticas están en los terminales axónicos, no en los nódulos.</p>`, conc: 'Conducción saltatoria: el impulso se regenera en los nódulos, donde están los canales de Na+.' },
    { enun: r`<p>En un laboratorio se estimula eléctricamente un axón aislado justo en su punto medio, y el impulso viaja hacia ambos extremos. Sin embargo, en el organismo el impulso nace al inicio del axón, junto al soma, y avanza solo hacia los terminales axónicos.</p><p>¿Qué impide que, en el organismo, el impulso se devuelva hacia el soma?</p>`, src: 'Estilo PAES',
      alts: ['La mielina solo deja pasar el impulso en un sentido.', 'La bomba Na<sup>+</sup>/K<sup>+</sup> empuja el impulso hacia los terminales.', 'El tramo que acaba de disparar queda en período refractario y no puede volver a excitarse de inmediato.', 'El axón solo tiene canales de Na<sup>+</sup> en sus terminales.'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Explicar por qué el impulso no retrocede.</p><p><b>Paso 2. Recuerda el período refractario.</b> Después de un potencial de acción, los canales de Na<sup>+</sup> de ese tramo quedan inactivados por un instante: aunque reciba un estímulo, no puede disparar otro potencial de acción.</p><p><b>Paso 3. Aplica.</b> El impulso despolariza a sus dos vecinos, pero el de atrás acaba de disparar y está refractario; solo el de adelante responde. Como el impulso nace al inicio del axón, avanza hacia los terminales. En el experimento, al estimular el punto medio, ningún vecino está refractario y por eso el impulso viaja hacia ambos lados.</p><p><b>Respuesta:</b> el tramo que acaba de disparar queda en período refractario.</p><p><b>¿Por qué no las otras?</b> La mielina aísla, pero no tiene un sentido: en el experimento el impulso viaja hacia ambos extremos de un axón que puede tener mielina. La bomba Na<sup>+</sup>/K<sup>+</sup> mantiene gradientes, no empuja impulsos. Los canales de Na<sup>+</sup> están a lo largo de todo el axón (o en todos sus nódulos), no solo en los terminales.</p>`, conc: 'El período refractario impide que el impulso se devuelva por el tramo que acaba de pasar.' }
  ]
},

/* =====================================================================
   TEMA 2 · SINAPSIS, ARCO REFLEJO Y CUIDADO DEL SISTEMA NERVIOSO
   ===================================================================== */
{
  id: 'bio_sinapsis', unit: 'Unidad 2 · Procesos y funciones biológicas', icon: '🔗',
  title: 'Sinapsis, arco reflejo y cuidado del sistema nervioso',
  desc: 'Cómo pasa la señal de una neurona a otra en la sinapsis química, cómo funciona el arco reflejo simple, cómo actúan la cafeína, el alcohol y las drogas de abuso sobre la sinapsis y qué cuidados protegen al sistema nervioso: dormir lo suficiente y prevenir traumatismos.',
  slides: [
    { t: 'La sinapsis química', b: r`
      <div class="cols"><div>
      <p>La <b>sinapsis</b> es la zona de comunicación entre una neurona y otra célula: otra neurona, un músculo o una glándula. En la <b>sinapsis química</b> las células no se tocan: las separa el <b>espacio sináptico</b>, de unos 20 a 40 nm.</p>
      <p>Paso a paso:</p>
      <ul><li>1. El potencial de acción llega al <b>terminal axónico</b> (neurona presináptica).</li>
      <li>2. Se abren <b>canales de Ca<sup>2+</sup></b> dependientes de voltaje y entra Ca<sup>2+</sup>.</li>
      <li>3. El Ca<sup>2+</sup> hace que las <b>vesículas sinápticas</b> se fusionen con la membrana y liberen el <b>neurotransmisor</b> por exocitosis.</li>
      <li>4. El neurotransmisor difunde y se une a <b>receptores</b> específicos de la membrana postsináptica.</li>
      <li>5. Los receptores abren canales iónicos y cambian el potencial de la célula postsináptica.</li></ul>
      </div><div>
      <div class="box"><b>Recuerda</b> Dentro de la neurona la señal es <b>eléctrica</b> (potencial de acción); en la sinapsis química es <b>química</b> (neurotransmisor). La sinapsis transmite en un solo sentido: solo el terminal presináptico tiene vesículas y solo la membrana postsináptica tiene los receptores.</div>
      </div></div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/ner_sinapsis.svg" alt="Sinapsis química: llega el potencial de acción al terminal axónico; entra Ca2+ por un canal; las vesículas sinápticas liberan neurotransmisor al espacio sináptico; el neurotransmisor se une a receptores de la neurona postsináptica; un transportador lo recapta hacia el terminal"></div>` },
    { t: 'Excitar, inhibir y apagar la señal', b: r`
      <div class="cols"><div>
      <p>Según el neurotransmisor y el receptor, la sinapsis puede ser:</p>
      <ul><li><b>Excitatoria:</b> el receptor deja entrar Na<sup>+</sup>, la membrana postsináptica se despolariza y se acerca al umbral. Ejemplo: el glutamato.</li>
      <li><b>Inhibitoria:</b> el receptor deja entrar Cl<sup>−</sup> (o salir K<sup>+</sup>), la membrana se hiperpolariza y se aleja del umbral. Ejemplo: el GABA.</li></ul>
      <p>Para que la sinapsis pueda transmitir un nuevo mensaje, el neurotransmisor debe <b>retirarse</b> del espacio sináptico. Hay dos formas principales:</p>
      <ul><li><b>Degradación enzimática:</b> una enzima lo destruye. La acetilcolinesterasa degrada la acetilcolina.</li>
      <li><b>Recaptación:</b> un transportador de la membrana presináptica lo devuelve al terminal para reutilizarlo. Así se retiran la dopamina, la serotonina y la noradrenalina.</li></ul>
      </div><div>
      <table><thead><tr><th>Neurotransmisor</th><th>Algunas funciones</th></tr></thead><tbody>
      <tr><td>Acetilcolina</td><td>contracción del músculo esquelético, memoria</td></tr>
      <tr><td>Dopamina</td><td>movimiento, motivación, circuito de recompensa</td></tr>
      <tr><td>Serotonina</td><td>ánimo, sueño, apetito</td></tr>
      <tr><td>Noradrenalina</td><td>alerta, respuesta simpática</td></tr>
      <tr><td>Glutamato</td><td>principal excitatorio del SNC, aprendizaje</td></tr>
      <tr><td>GABA</td><td>principal inhibitorio del SNC</td></tr></tbody></table>
      <div class="box"><b>Recuerda</b> Si algo impide retirar el neurotransmisor (bloquea la enzima o la recaptación), este se queda más tiempo en el espacio sináptico y la célula postsináptica se estimula por más tiempo.</div>
      </div></div>` },
    { t: 'El arco reflejo', b: r`
      <div class="cols"><div>
      <p>Un <b>reflejo</b> es una respuesta <b>rápida, involuntaria y predecible</b> frente a un estímulo: retirar la mano de una olla caliente, el reflejo rotuliano, el parpadeo. El camino que sigue el impulso es el <b>arco reflejo</b>, con cinco componentes:</p>
      <ul><li><b>Receptor:</b> capta el estímulo (en la piel, un receptor de dolor o de calor).</li>
      <li><b>Vía aferente:</b> una neurona sensitiva lleva el impulso hacia el SNC. Entra a la médula por la raíz dorsal; su soma está en un ganglio.</li>
      <li><b>Centro elaborador:</b> la médula espinal (o el tronco encefálico). Ahí la información pasa, a menudo a través de una interneurona, a una neurona motora.</li>
      <li><b>Vía eferente:</b> una neurona motora lleva la orden hacia el efector.</li>
      <li><b>Efector:</b> el músculo que se contrae o la glándula que secreta.</li></ul>
      </div><div>
      <div class="box"><b>¿Por qué es tan rápido?</b> La respuesta se elabora en la médula, con muy pocas sinapsis, sin esperar al encéfalo. Al mismo tiempo, la información sube por la médula hasta el encéfalo: por eso sientes el dolor un instante <b>después</b> de haber retirado la mano.</div>
      <div class="box"><b>Recuerda</b> El reflejo rotuliano es el arco más simple: la neurona sensitiva hace sinapsis directamente con la neurona motora, sin interneurona.</div>
      </div></div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/ner_arco.svg" alt="Arco reflejo: un estímulo actúa sobre un receptor en la piel; la neurona sensitiva, con su cuerpo en un ganglio, lleva el impulso a la médula espinal; ahí una interneurona lo pasa a la neurona motora, que lleva la orden al músculo efector"></div>` },
    { t: 'El café y la cafeína', b: r`
      <div class="cols"><div>
      <p>Mientras estamos despiertos, la actividad del encéfalo acumula <b>adenosina</b>. La adenosina se une a sus receptores en las neuronas y <b>disminuye</b> su actividad: así aparece la sensación de cansancio y sueño.</p>
      <p>La <b>cafeína</b> (del café, el té, el mate, las bebidas cola y las bebidas energéticas) tiene una forma parecida a la adenosina. Se une a los receptores de adenosina <b>sin activarlos</b> y los bloquea. Resultado: la adenosina no puede actuar, y la persona se siente más alerta y con menos sueño.</p>
      <p>La cafeína tarda unas 5 horas en reducirse a la mitad en la sangre. Por eso un café en la tarde puede retrasar el sueño en la noche.</p>
      </div><div>
      <div class="box"><b>Efectos del consumo alto</b> Insomnio, nerviosismo, ansiedad, taquicardia y molestias digestivas. Con el consumo diario aparece <b>tolerancia</b> (se necesita más para el mismo efecto), y al suspenderlo puede haber dolor de cabeza y cansancio por un par de días.</div>
      </div></div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/ner_cafeina.svg" alt="Dos paneles. Sin cafeína: la adenosina se une a sus receptores y la actividad de la neurona disminuye, lo que produce sensación de sueño. Con cafeína: la cafeína ocupa los receptores sin activarlos, la adenosina no se une y la actividad de la neurona se mantiene"></div>` },
    { t: 'Alcohol y drogas de abuso', b: r`
      <p>Muchas sustancias alteran la conducta porque actúan sobre la sinapsis: imitan a un neurotransmisor, bloquean sus receptores o cambian cuánto tiempo permanece en el espacio sináptico.</p>
      <table><thead><tr><th>Sustancia</th><th>Acción sobre la sinapsis</th><th>Efectos</th></tr></thead><tbody>
      <tr><td>Alcohol (etanol)</td><td>aumenta el efecto del GABA (inhibitorio) y reduce el del glutamato (excitatorio)</td><td>depresor del SNC: reflejos más lentos, falta de coordinación, peor juicio; en dosis altas, pérdida de conciencia y depresión respiratoria</td></tr>
      <tr><td>Nicotina</td><td>se une a receptores de acetilcolina y aumenta la liberación de dopamina</td><td>estimulante, muy adictiva</td></tr>
      <tr><td>Cocaína</td><td>bloquea la recaptación de dopamina, noradrenalina y serotonina</td><td>euforia, taquicardia, hipertensión; alto riesgo de adicción</td></tr>
      <tr><td>Anfetaminas</td><td>aumentan la liberación de dopamina y noradrenalina</td><td>estimulantes: alerta, insomnio, taquicardia</td></tr>
      <tr><td>Marihuana (THC)</td><td>se une a receptores cannabinoides</td><td>altera la memoria, la atención y la coordinación</td></tr></tbody></table>
      <div class="box" style="margin-top:14px"><b>Tolerancia y dependencia</b> Las drogas de abuso aumentan la dopamina en el <b>circuito de recompensa</b> del encéfalo. Con el consumo repetido, las neuronas se adaptan (por ejemplo, disminuyen sus receptores): aparece la <b>tolerancia</b>, y al dejar la sustancia, el <b>síndrome de abstinencia</b>. Este cambio en el circuito de recompensa es la base de la adicción.</div>
      <div class="box" style="margin-top:14px"><b>Alcohol y conducción en Chile</b> La ley considera «bajo la influencia del alcohol» a quien conduce con más de 0,3 g de alcohol por litro de sangre, y «en estado de ebriedad» desde 0,8 g/L. El alcohol alarga el tiempo de reacción incluso en dosis bajas.</div>` },
    { t: 'Cuidar el sistema nervioso', b: r`
      <div class="cols"><div>
      <p><b>Dormir lo suficiente.</b> Durante el sueño el encéfalo consolida lo aprendido en el día (la memoria) y se recupera. Dormir poco empeora la atención, la memoria, el ánimo y el tiempo de reacción.</p>
      <table><thead><tr><th>Edad</th><th>Horas de sueño recomendadas</th></tr></thead><tbody>
      <tr><td>6 a 12 años</td><td>9 a 12 h</td></tr>
      <tr><td>13 a 18 años</td><td>8 a 10 h</td></tr>
      <tr><td>Adultos</td><td>7 a 9 h</td></tr></tbody></table>
      <p>Ayudan a dormir bien: horarios regulares, evitar pantallas antes de acostarse y no tomar cafeína en la tarde.</p>
      </div><div>
      <p><b>Prevenir traumatismos.</b> Las neuronas del SNC casi no se reemplazan cuando mueren: un daño en el encéfalo o en la médula espinal suele dejar secuelas permanentes.</p>
      <ul><li><b>Traumatismo encéfalo craneano (TEC):</b> golpe en la cabeza en accidentes de tránsito, caídas o deportes. Se previene con <b>casco</b> (bicicleta, scooter, moto, esquí) y <b>cinturón de seguridad</b>, y con sillas para niños en el auto.</li>
      <li><b>Lesión de la médula espinal:</b> se pierde la sensibilidad y el movimiento voluntario de las zonas del cuerpo que dependen de la médula bajo la lesión. Una causa frecuente en verano es lanzarse de cabeza en aguas poco profundas.</li></ul>
      </div></div>` },
    { t: 'Lo clave del tema', b: r`
      <table><thead><tr><th>Si una sustancia…</th><th>…entonces en la sinapsis…</th><th>Ejemplo</th></tr></thead><tbody>
      <tr><td>bloquea los canales de Ca<sup>2+</sup> del terminal</td><td>se libera menos neurotransmisor</td><td>algunas toxinas</td></tr>
      <tr><td>bloquea los receptores postsinápticos</td><td>el neurotransmisor no tiene efecto</td><td>cafeína con los receptores de adenosina</td></tr>
      <tr><td>imita al neurotransmisor</td><td>activa los receptores</td><td>nicotina con los de acetilcolina</td></tr>
      <tr><td>bloquea la recaptación</td><td>el neurotransmisor dura más en el espacio sináptico</td><td>cocaína con la dopamina</td></tr>
      <tr><td>bloquea la enzima que degrada</td><td>el neurotransmisor dura más en el espacio sináptico</td><td>inhibidores de la acetilcolinesterasa</td></tr></tbody></table>
      <div class="box" style="margin-top:14px"><b>Recuerda</b><br>· Arco reflejo: receptor → vía aferente → centro elaborador (médula) → vía eferente → efector.<br>· El reflejo es involuntario y rápido porque se elabora en la médula, sin esperar al encéfalo.<br>· La cafeína bloquea los receptores de adenosina; el alcohol es un depresor del SNC.<br>· Adolescentes: 8 a 10 horas de sueño. Casco y cinturón previenen traumatismos.</div>
      <div class="box" style="margin-top:14px"><b>Método PAES</b> 1. Ubica en qué paso de la sinapsis actúa la sustancia: liberación, unión al receptor o retiro del neurotransmisor. 2. Deduce si el neurotransmisor queda en mayor o menor cantidad, o por más o menos tiempo. 3. En un arco reflejo, sigue el camino del impulso y fíjate qué parte quedó cortada: lo que está antes del corte sigue funcionando. 4. En un experimento, busca el grupo control y la variable que se mide.</div>` }
  ],
  example: {
    src: 'Estilo PAES',
    enun: r`<p>El siguiente esquema representa una sinapsis química. Los números indican algunas de sus estructuras.</p><p>Un fármaco bloquea la estructura 5. ¿Qué efecto directo tendrá sobre esta sinapsis?</p>`,
    fig: { type: 'img', src: 'paes/biologia/fig/ner_sinapsis_num.svg', alt: 'Sinapsis química con cinco estructuras numeradas: 1, vesícula con neurotransmisor dentro del terminal axónico; 2, moléculas de neurotransmisor en el espacio sináptico; 3, receptor en la membrana de la neurona postsináptica; 4, transportador en la membrana del terminal, con una flecha que va del espacio sináptico al terminal; 5, canal en la membrana del terminal, con una flecha de entrada de iones hacia el terminal' },
    alts: ['Disminuirá la liberación de neurotransmisor desde las vesículas.', 'El neurotransmisor no podrá unirse a la estructura 3.', 'Aumentará la recaptación del neurotransmisor.', 'Se impedirá la propagación del potencial de acción a lo largo del axón.'], ok: 0,
    sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El efecto de bloquear la estructura 5.</p><p><b>Paso 2. Identifica la estructura.</b> La 5 es un canal en la membrana del terminal axónico por el que entran iones cuando llega el potencial de acción: es el <b>canal de Ca<sup>2+</sup></b> dependiente de voltaje.</p><p><b>Paso 3. ¿Para qué sirve el Ca<sup>2+</sup>?</b> La entrada de Ca<sup>2+</sup> es la señal para que las vesículas (1) se fusionen con la membrana y liberen el neurotransmisor. Sin Ca<sup>2+</sup>, las vesículas casi no se fusionan.</p><p><b>Respuesta:</b> disminuirá la liberación de neurotransmisor.</p><p><b>¿Por qué no las otras?</b> El receptor (3) está en la neurona postsináptica y no se ve afectado; el problema es que le llega menos neurotransmisor. El transportador de recaptación (4) es otra proteína y nada indica que funcione más. El potencial de acción viaja por el axón gracias a los canales de Na<sup>+</sup> y K<sup>+</sup>: sí llega al terminal, pero ahí no logra liberar el neurotransmisor.</p>`,
    conc: 'Sin entrada de Ca2+ al terminal, las vesículas no liberan el neurotransmisor.'
  },
  bank: [
    /* Tipo 1: estructura y funcionamiento de la sinapsis química (Invierno 2026 n.º 5 y n.º 57) */
    { enun: r`<p>Observa el esquema de una sinapsis química.</p><p>¿Qué número indica la estructura a la que se une el neurotransmisor para producir un cambio en la neurona postsináptica y cuál la que lo devuelve a la neurona presináptica, respectivamente?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_sinapsis_num.svg', alt: 'Sinapsis química con cinco estructuras numeradas: 1, vesícula con neurotransmisor dentro del terminal axónico; 2, moléculas de neurotransmisor en el espacio sináptico; 3, receptor en la membrana de la neurona postsináptica; 4, transportador en la membrana del terminal, con una flecha que va del espacio sináptico al terminal; 5, canal en la membrana del terminal, con una flecha de entrada de iones hacia el terminal' },
      alts: ['1 y 4', '3 y 4', '3 y 5', '2 y 1'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Dos estructuras: el receptor postsináptico y el transportador de recaptación.</p><p><b>Paso 2. Identifica cada número.</b> 1: vesícula sináptica. 2: neurotransmisor en el espacio sináptico. 3: receptor de la membrana postsináptica. 4: transportador de recaptación (su flecha va del espacio sináptico al terminal). 5: canal de Ca<sup>2+</sup>.</p><p><b>Respuesta:</b> 3 y 4.</p><p><b>¿Por qué no las otras?</b> La 1 es la vesícula que almacena el neurotransmisor, no un receptor. La 5 es el canal por donde entra Ca<sup>2+</sup>, no el neurotransmisor. El 2 es el propio neurotransmisor, y la vesícula (1) no lo recapta desde el espacio sináptico.</p>`, conc: 'El receptor está en la membrana postsináptica; el transportador de recaptación, en la presináptica.' },
    { enun: r`<p>En una sinapsis química entre dos neuronas, A y B, el impulso pasa siempre de A hacia B y nunca de B hacia A.</p><p>¿Qué explica que la transmisión ocurra en un solo sentido?</p>`, src: 'Estilo PAES',
      alts: ['El espacio sináptico solo deja difundir iones desde A hacia B.', 'El potencial de acción salta directamente de la membrana de A a la de B.', 'Solo el terminal de A tiene vesículas con neurotransmisor y solo la membrana de B tiene receptores para él.', 'La neurona B no tiene canales iónicos en su membrana.'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> La razón de que la sinapsis química sea unidireccional.</p><p><b>Paso 2. Recuerda la asimetría.</b> La neurona presináptica (A) tiene en su terminal las vesículas con el neurotransmisor y los canales de Ca<sup>2+</sup> que permiten liberarlo. La neurona postsináptica (B) tiene en su membrana los <b>receptores</b> para ese neurotransmisor. Si B se excita, no tiene vesículas que liberen neurotransmisor hacia A en esa sinapsis, y A no tiene los receptores.</p><p><b>Respuesta:</b> solo el terminal de A tiene vesículas y solo la membrana de B tiene receptores.</p><p><b>¿Por qué no las otras?</b> El espacio sináptico es líquido extracelular: las moléculas difunden en todas direcciones. En una sinapsis química el potencial de acción no salta de una membrana a otra: la señal se transmite por el neurotransmisor. La neurona B sí tiene canales iónicos; sin ellos no podría responder.</p>`, conc: 'La sinapsis química es unidireccional: vesículas en la presináptica, receptores en la postsináptica.' },
    { enun: r`<p>Hacia 1900, Ramón y Cajal sostenía que las neuronas no están unidas entre sí, y en 1897 Charles Sherrington ya había llamado «sinapsis» a la zona donde se comunican. Sin embargo, el espacio que separa dos neuronas en una sinapsis química (de unos 20 nm) recién pudo observarse directamente en la década de 1950.</p><p>¿Qué aspecto procedimental explica esta demora?</p>`, src: 'PAES Invierno 2026, adaptada',
      alts: ['No existía una teoría que propusiera que las neuronas se comunican en una zona especial.', 'Se desconocía que el encéfalo participa en el control del cuerpo.', 'Aún no se había descubierto ningún neurotransmisor.', 'El microscopio óptico no permite distinguir un espacio tan pequeño; fue necesario el microscopio electrónico.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Un aspecto <b>procedimental</b>: algo relacionado con las técnicas o instrumentos de investigación, no con las ideas.</p><p><b>Paso 2. Compara tamaños.</b> El microscopio óptico no distingue detalles menores a unos 200 nm. Un espacio de 20 nm es diez veces más pequeño: con luz visible, las dos membranas se ven como si se tocaran. El microscopio electrónico, que se usó en biología desde mediados del siglo XX, sí tiene la resolución necesaria.</p><p><b>Respuesta:</b> el microscopio óptico no permite distinguir un espacio tan pequeño; fue necesario el microscopio electrónico.</p><p><b>¿Por qué no las otras?</b> Sí existía la teoría: el propio enunciado dice que Sherrington ya había propuesto la sinapsis. Que el encéfalo controla el cuerpo se sabía desde mucho antes. Además, estas dos opciones son conceptuales, no procedimentales. El primer neurotransmisor, la acetilcolina, se identificó en la década de 1920, antes de 1950, y su descubrimiento no permitía ver el espacio sináptico.</p>`, conc: 'Ver el espacio sináptico (unos 20 nm) requirió el microscopio electrónico.' },
    { enun: r`<p>Algunos insecticidas inhiben la acetilcolinesterasa, la enzima que degrada la acetilcolina en el espacio sináptico entre una neurona motora y una fibra muscular.</p><p>¿Qué efecto directo tiene esta inhibición en la sinapsis?</p>`, src: 'PAES Invierno 2026, adaptada',
      alts: ['La acetilcolina permanece más tiempo en el espacio sináptico y el músculo recibe una estimulación prolongada.', 'La neurona motora libera menos acetilcolina.', 'Los receptores de acetilcolina del músculo desaparecen.', 'El músculo se relaja por completo porque no le llega acetilcolina.'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El efecto de inhibir la enzima que retira la acetilcolina.</p><p><b>Paso 2. ¿Qué hace la enzima?</b> Degrada la acetilcolina después de que actúa, para que la señal termine.</p><p><b>Paso 3. Sin enzima.</b> La acetilcolina no se degrada y sigue uniéndose a los receptores del músculo. El músculo recibe estimulación por más tiempo: aparecen contracciones involuntarias y espasmos.</p><p><b>Respuesta:</b> la acetilcolina permanece más tiempo en el espacio sináptico y el músculo recibe una estimulación prolongada.</p><p><b>¿Por qué no las otras?</b> La enzima actúa después de la liberación: inhibirla no cambia cuánta acetilcolina se libera. Tampoco elimina los receptores. El músculo no se relaja por falta de acetilcolina; al contrario, hay acetilcolina de sobra.</p>`, conc: 'Si no se degrada el neurotransmisor, su efecto se prolonga.' },

    /* Tipo 2: arco reflejo simple */
    { enun: r`<p>El esquema representa un arco reflejo. Los números indican sus componentes.</p><p>¿Qué números corresponden al centro elaborador y a la vía eferente, respectivamente?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_arco_num.svg', alt: 'Arco reflejo con cinco componentes numerados: 1, terminación nerviosa en la piel que recibe un estímulo; 2, neurona que va de la piel a la médula espinal pasando por un ganglio; 3, interneurona dentro de la médula espinal; 4, neurona que va de la médula espinal al músculo; 5, músculo' },
      alts: ['2 y 4', '3 y 2', '3 y 4', '5 y 4'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El centro elaborador y la vía eferente.</p><p><b>Paso 2. Sigue el camino del impulso.</b> 1: receptor en la piel. 2: neurona sensitiva, que lleva el impulso hacia la médula (vía aferente). 3: interneurona en la médula espinal (centro elaborador). 4: neurona motora, que lleva la orden desde la médula (vía eferente). 5: músculo (efector).</p><p><b>Respuesta:</b> 3 y 4.</p><p><b>¿Por qué no las otras?</b> El 2 es la vía aferente: lleva el impulso <b>hacia</b> el centro, no desde él. El 5 es el efector, el músculo que responde, no el centro elaborador.</p>`, conc: 'Aferente llega al centro; eferente sale del centro hacia el efector.' },
    { enun: r`<p>En un accidente, una persona sufre un corte que interrumpe únicamente la estructura 4 del arco reflejo representado. Las vías que suben por la médula espinal hasta el encéfalo están intactas.</p><p>Si se le pincha la piel en la zona del receptor, ¿qué se espera?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_arco_num.svg', alt: 'Arco reflejo con cinco componentes numerados: 1, terminación nerviosa en la piel que recibe un estímulo; 2, neurona que va de la piel a la médula espinal pasando por un ganglio; 3, interneurona dentro de la médula espinal; 4, neurona que va de la médula espinal al músculo; 5, músculo' },
      alts: ['No siente el pinchazo y tampoco se produce el movimiento reflejo.', 'Se produce el movimiento reflejo, pero no siente el pinchazo.', 'El movimiento reflejo se produce más rápido de lo normal.', 'Siente el pinchazo, pero no se produce el movimiento reflejo.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Qué pasa con la sensación y con el reflejo si se corta la estructura 4.</p><p><b>Paso 2. Identifica la estructura.</b> La 4 es la neurona motora, la vía eferente: lleva la orden desde la médula hasta el músculo.</p><p><b>Paso 3. Sigue el impulso.</b> El receptor (1), la vía aferente (2) y la médula (3) funcionan: la información llega a la médula y desde ahí sube al encéfalo, así que la persona <b>siente</b> el pinchazo. Pero la orden no llega al músculo porque la vía eferente está cortada: <b>no hay movimiento reflejo</b>.</p><p><b>Respuesta:</b> siente el pinchazo, pero no se produce el movimiento reflejo.</p><p><b>¿Por qué no las otras?</b> La primera opción correspondería a un corte de la vía aferente (2), antes de la médula. El reflejo no puede ocurrir si el músculo no recibe la orden. Cortar una vía no acelera la respuesta.</p>`, conc: 'Lo que está antes del corte funciona; lo que está después, no.' },
    { enun: r`<p>Al golpear suavemente el tendón bajo la rodilla, la pierna se extiende de forma involuntaria: es el reflejo rotuliano.</p><p>¿Qué secuencia representa el recorrido del impulso en este reflejo?</p>`, src: 'Estilo PAES',
      alts: ['Efector → neurona motora → médula espinal → neurona sensitiva → receptor.', 'Receptor → neurona sensitiva → médula espinal → neurona motora → efector.', 'Receptor → neurona motora → encéfalo → neurona sensitiva → efector.', 'Receptor → médula espinal → neurona sensitiva → efector → neurona motora.'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El orden de los componentes del arco reflejo.</p><p><b>Paso 2. Ordénalos.</b> El estímulo lo capta el <b>receptor</b> (en el músculo del muslo, que se estira con el golpe). La <b>neurona sensitiva</b> lleva el impulso a la <b>médula espinal</b>, donde hace sinapsis con la <b>neurona motora</b>, que lleva la orden al <b>efector</b>: el músculo del muslo, que se contrae y extiende la pierna.</p><p><b>Respuesta:</b> receptor → neurona sensitiva → médula espinal → neurona motora → efector.</p><p><b>¿Por qué no las otras?</b> La primera tiene el orden invertido. La tercera pone la neurona motora antes del centro y lleva el impulso al encéfalo; el reflejo rotuliano se elabora en la médula. La cuarta pone la médula antes de la neurona sensitiva, que es la que lleva el impulso hasta ella.</p>`, conc: 'Arco reflejo: receptor → sensitiva → médula → motora → efector.' },
    { enun: r`<p>Una persona toca sin querer una olla muy caliente y retira la mano de inmediato. Un instante después siente el dolor de la quemadura.</p><p>¿Qué explica que retire la mano antes de sentir el dolor?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_arco.svg', alt: 'Arco reflejo: un estímulo actúa sobre un receptor en la piel; la neurona sensitiva, con su cuerpo en un ganglio, lleva el impulso a la médula espinal; ahí una interneurona lo pasa a la neurona motora, que lleva la orden al músculo efector' },
      alts: ['La respuesta se elabora en la médula espinal, con pocas sinapsis, sin esperar que la información llegue al encéfalo.', 'La neurona motora se activa antes que el receptor de la piel.', 'El encéfalo decide retirar la mano y después envía la información de dolor a la médula.', 'La información de dolor viaja por la neurona motora, que es más rápida que la sensitiva.'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Por qué la respuesta ocurre antes de la sensación consciente.</p><p><b>Paso 2. Mira el arco reflejo.</b> El impulso va del receptor a la médula espinal y, a través de una interneurona, pasa directamente a la neurona motora. El camino es corto y tiene pocas sinapsis.</p><p><b>Paso 3. ¿Y el dolor?</b> La sensación de dolor se produce en el encéfalo. La información debe subir por la médula hasta él, un camino más largo y con más sinapsis. Por eso el dolor se siente después del movimiento.</p><p><b>Respuesta:</b> la respuesta se elabora en la médula espinal, sin esperar al encéfalo.</p><p><b>¿Por qué no las otras?</b> La neurona motora se activa después del receptor: el impulso siempre parte en el receptor. En un reflejo el encéfalo no decide la respuesta. La neurona motora lleva órdenes hacia el músculo, no información de dolor.</p>`, conc: 'El reflejo se elabora en la médula: la mano se retira antes de que el encéfalo perciba el dolor.' },

    /* Tipo 3: café, alcohol y drogas de abuso (Regular 2026 n.º 4, Invierno 2027 n.º 10 y n.º 59) */
    { enun: r`<p>Un grupo de investigación mide la concentración de dopamina en el espacio sináptico después de un impulso nervioso, sin tratamiento (control) y en presencia de una sustancia S. Los resultados se muestran en el gráfico.</p><p>¿Qué mecanismo de acción de S es consistente con estos resultados?</p>`, src: 'PAES Invierno 2027, adaptada',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_graf_dopamina.svg', alt: 'Gráfico de dopamina en el espacio sináptico versus tiempo: en ambos casos la dopamina sube hasta 1 a los 20 ms; en el control baja rápido y llega casi a cero a los 150 ms; con la sustancia S baja muy lentamente y a los 400 ms todavía está cerca de 0,1' },
      alts: ['S aumenta la actividad de las enzimas que degradan la dopamina.', 'S impide que las vesículas liberen dopamina.', 'S bloquea los receptores de dopamina de la neurona postsináptica.', 'S bloquea el transportador que recapta la dopamina hacia el terminal presináptico.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Un mecanismo que explique el gráfico.</p><p><b>Paso 2. Lee el gráfico.</b> En ambos casos se libera la misma cantidad de dopamina (el máximo es igual). La diferencia está en la bajada: con S, la dopamina <b>permanece mucho más tiempo</b> en el espacio sináptico.</p><p><b>Paso 3. ¿Qué retira la dopamina?</b> Principalmente la <b>recaptación</b>: un transportador la devuelve al terminal presináptico. Si S bloquea el transportador, la dopamina se queda más tiempo. Así actúa la cocaína.</p><p><b>Respuesta:</b> S bloquea el transportador que recapta la dopamina.</p><p><b>¿Por qué no las otras?</b> Si aumentara la degradación, la dopamina desaparecería más rápido, no más lento. Si se impidiera la liberación, el máximo sería menor. Bloquear los receptores postsinápticos impediría el efecto de la dopamina, pero no cambiaría cuánto tiempo permanece en el espacio sináptico.</p>`, conc: 'Neurotransmisor que dura más en el espacio sináptico: se bloqueó su recaptación o su degradación.' },
    { enun: r`<p>El esquema compara lo que ocurre en los receptores de adenosina de una neurona sin cafeína y con cafeína.</p><p>¿Qué explica que una persona que toma café sienta menos sueño?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_cafeina.svg', alt: 'Dos paneles. Sin cafeína: la adenosina se une a sus receptores y la actividad de la neurona disminuye, lo que produce sensación de sueño. Con cafeína: la cafeína ocupa los receptores sin activarlos, la adenosina no se une y la actividad de la neurona se mantiene' },
      alts: ['La cafeína se une a los receptores de adenosina y los activa con más fuerza que la adenosina.', 'La cafeína ocupa los receptores de adenosina sin activarlos, y la adenosina no puede disminuir la actividad neuronal.', 'La cafeína destruye la adenosina acumulada en el encéfalo.', 'La cafeína aumenta la producción de adenosina en las neuronas.'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El mecanismo por el que la cafeína reduce el sueño.</p><p><b>Paso 2. Lee el esquema.</b> Sin cafeína, la adenosina se une a sus receptores y la actividad neuronal disminuye: aparece el sueño. Con cafeína, la cafeína ocupa esos receptores y la adenosina queda libre, sin poder unirse.</p><p><b>Paso 3. Concluye.</b> La cafeína es un <b>antagonista</b>: se une al receptor pero no lo activa, y así bloquea el efecto de la adenosina.</p><p><b>Respuesta:</b> la cafeína ocupa los receptores de adenosina sin activarlos.</p><p><b>¿Por qué no las otras?</b> Si la cafeína activara los receptores de adenosina, produciría más sueño, no menos. En el esquema la adenosina sigue presente: no se destruye. Más adenosina produciría más sueño.</p>`, conc: 'La cafeína bloquea los receptores de adenosina: la señal de cansancio no llega.' },
    { enun: r`<p>En un estudio, voluntarios adultos consumieron distintas cantidades de alcohol y luego se les midió el tiempo que tardaban en apretar un botón al ver una luz (tiempo de reacción). Los resultados promedio se muestran en el gráfico.</p><p>¿Qué conclusión se apoya en estos datos?</p>`, src: 'PAES Invierno 2027, adaptada',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_graf_alcohol.svg', alt: 'Gráfico de tiempo de reacción versus alcohol en la sangre: 250 ms con 0 g/L, 258 ms con 0,2 g/L, 270 ms con 0,4 g/L, 288 ms con 0,6 g/L, 310 ms con 0,8 g/L, 335 ms con 1,0 g/L y 365 ms con 1,2 g/L' },
      alts: ['El alcohol no modifica el tiempo de reacción mientras la concentración sea menor que 0,8 g/L.', 'El tiempo de reacción disminuye a medida que aumenta el alcohol en la sangre.', 'A medida que aumenta el alcohol en la sangre aumenta el tiempo de reacción, incluso en concentraciones menores que 0,8 g/L.', 'El alcohol es un estimulante del sistema nervioso, porque cambia la velocidad de respuesta.'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Una conclusión que se desprenda del gráfico.</p><p><b>Paso 2. Lee la tendencia.</b> Sin alcohol, el tiempo de reacción es 250 ms. Con 0,4 g/L ya es 270 ms y con 0,8 g/L, 310 ms. La curva siempre sube: a más alcohol, <b>más tiempo</b> tarda la respuesta.</p><p><b>Respuesta:</b> a medida que aumenta el alcohol en la sangre, aumenta el tiempo de reacción, incluso bajo 0,8 g/L.</p><p><b>¿Por qué no las otras?</b> Bajo 0,8 g/L el tiempo ya aumenta (de 250 a 288 ms en 0,6 g/L). El tiempo de reacción aumenta, no disminuye. El alcohol es un <b>depresor</b> del sistema nervioso: hace las respuestas más lentas. Esto explica por qué la ley chilena sanciona conducir desde 0,3 g/L.</p>`, conc: 'El alcohol es depresor: alarga el tiempo de reacción aun en dosis bajas.' },
    { enun: r`<p>Un grupo de estudiantes quiere saber si la cafeína disminuye el tiempo de reacción. Forman tres grupos de compañeros: uno toma una bebida con 50 mg de cafeína, otro con 100 mg y otro con 200 mg. Una hora después miden el tiempo de reacción de cada uno y concluyen que la cafeína lo disminuye, porque los tres grupos tuvieron tiempos bajos.</p><p>¿Qué error del diseño impide sacar esa conclusión?</p>`, src: 'PAES Regular 2026, adaptada',
      alts: ['Faltó un grupo que tomara la misma bebida, pero sin cafeína.', 'Faltó probar dosis de cafeína mayores que 200 mg.', 'Faltó probar dosis de cafeína menores que 50 mg.', 'Faltó medir el tiempo de reacción en otros horarios del día.'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El error que impide afirmar que la cafeína disminuye el tiempo de reacción.</p><p><b>Paso 2. ¿Con qué comparan?</b> Para decir que algo <b>disminuye</b>, hay que comparar con una situación sin el factor estudiado. Aquí todos los grupos tomaron cafeína: no hay un <b>grupo control</b>.</p><p><b>Paso 3. El grupo control adecuado.</b> Un grupo que tome la misma bebida pero sin cafeína (placebo), en las mismas condiciones. Así, cualquier diferencia se puede atribuir a la cafeína y no a la bebida, a la hora o a las expectativas.</p><p><b>Respuesta:</b> faltó un grupo que tomara la misma bebida, pero sin cafeína.</p><p><b>¿Por qué no las otras?</b> Probar más dosis, mayores o menores, no resuelve el problema: seguiría sin haber con qué comparar. Medir en otros horarios agrega información, pero tampoco reemplaza al grupo control.</p>`, conc: 'Para afirmar un efecto, necesitas un grupo control sin el factor estudiado.' },

    /* Tipo 4: cuidados del sistema nervioso (sueño y traumatismos) */
    { enun: r`<p>Un grupo de estudiantes de 16 años memorizó una lista de palabras en la tarde. Esa noche durmieron 4, 6 u 8 horas, según el grupo, y a la mañana siguiente se les pidió recordar la lista. El gráfico muestra los resultados promedio.</p><p>¿Qué conclusión se apoya en estos datos?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/ner_graf_sueno.svg', alt: 'Gráfico de barras de palabras recordadas según las horas de sueño la noche anterior: 48 % con 4 horas, 62 % con 6 horas y 80 % con 8 horas' },
      alts: ['Dormir 4 horas no afecta la memoria de los estudiantes.', 'Los estudiantes que durmieron 8 horas recordaron más palabras que los que durmieron menos.', 'Dormir más de 8 horas siempre mejora aún más la memoria.', 'El sueño no influye en lo que se aprende durante el día.'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Una conclusión que no vaya más allá de los datos.</p><p><b>Paso 2. Lee el gráfico.</b> Con 4 horas recordaron el 48 %; con 6 horas, el 62 %; con 8 horas, el 80 %. El grupo que durmió 8 horas recordó más.</p><p><b>Paso 3. Relaciona con la biología.</b> Durante el sueño se consolida la memoria. A los 16 años se recomiendan entre 8 y 10 horas de sueño.</p><p><b>Respuesta:</b> los estudiantes que durmieron 8 horas recordaron más palabras que los que durmieron menos.</p><p><b>¿Por qué no las otras?</b> Con 4 horas se recordó mucho menos: sí afecta. No se midió qué pasa con más de 8 horas, así que no se puede afirmar nada sobre eso. Los datos muestran justamente que el sueño influye en lo que se recuerda de lo aprendido.</p>`, conc: 'Dormir lo suficiente consolida la memoria; adolescentes: 8 a 10 horas.' },
    { enun: r`<p>Las campañas de seguridad vial recomiendan usar casco al andar en bicicleta o en scooter, aunque el trayecto sea corto.</p><p>¿Qué argumento biológico respalda esta recomendación?</p>`, src: 'Estilo PAES',
      alts: ['Las neuronas del encéfalo se dividen rápidamente y reemplazan a las que se dañan en un golpe.', 'El cráneo no ofrece protección al encéfalo, por lo que el casco cumple esa función.', 'El casco aumenta el flujo de sangre hacia el encéfalo durante el ejercicio.', 'El casco absorbe parte de la energía del impacto, y las neuronas del encéfalo que mueren casi no se reemplazan.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Una razón biológica para usar casco.</p><p><b>Paso 2. ¿Qué hace el casco?</b> En un golpe, absorbe y reparte parte de la energía del impacto. Así disminuye el riesgo de un traumatismo encéfalo craneano (TEC).</p><p><b>Paso 3. ¿Por qué importa tanto?</b> Las neuronas del sistema nervioso central casi no se reemplazan cuando mueren. Un daño en el encéfalo puede dejar secuelas permanentes en el movimiento, el habla o la memoria.</p><p><b>Respuesta:</b> el casco absorbe parte de la energía del impacto, y las neuronas que mueren casi no se reemplazan.</p><p><b>¿Por qué no las otras?</b> Las neuronas maduras casi no se dividen: esa es justamente la razón para prevenir. El cráneo sí protege el encéfalo, pero ante impactos fuertes no basta. El casco no tiene efecto sobre el flujo de sangre.</p>`, conc: 'Las neuronas del SNC casi no se reemplazan: prevenir traumatismos con casco y cinturón.' },
    { enun: r`<p>En verano, un joven se lanza de cabeza a una piscina de poca profundidad, se golpea contra el fondo y sufre una lesión que corta la médula espinal a la altura del cuello.</p><p>¿Qué consecuencia es esperable?</p>`, src: 'Estilo PAES',
      alts: ['Pierde solo la sensibilidad de la cabeza y la cara.', 'Pierde la visión, porque la médula espinal procesa la información de los ojos.', 'Pierde la sensibilidad y el movimiento voluntario de las partes del cuerpo que dependen de la médula bajo la lesión.', 'No hay consecuencias, porque los reflejos de la médula funcionan sin el encéfalo.'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El efecto de cortar la médula espinal a nivel del cuello.</p><p><b>Paso 2. ¿Qué hace la médula?</b> Además de ser centro de reflejos, es la <b>vía de comunicación</b> entre el encéfalo y el cuerpo: por ella sube la información sensitiva y bajan las órdenes de movimiento voluntario.</p><p><b>Paso 3. Aplica.</b> Si se corta en el cuello, la información de las zonas que dependen de la médula bajo la lesión ya no llega al encéfalo (no hay sensibilidad) y las órdenes del encéfalo no llegan a esos músculos (no hay movimiento voluntario).</p><p><b>Respuesta:</b> pierde la sensibilidad y el movimiento voluntario de las partes del cuerpo que dependen de la médula bajo la lesión.</p><p><b>¿Por qué no las otras?</b> La cabeza y la cara reciben nervios craneales que no pasan por la zona dañada. La visión depende de los nervios ópticos y del encéfalo, no de la médula. Algunos reflejos medulares pueden persistir bajo la lesión, pero eso no impide la pérdida de sensibilidad y de movimiento voluntario.</p>`, conc: 'La médula comunica encéfalo y cuerpo: si se corta, se pierde sensibilidad y movimiento bajo la lesión.' }
  ]
}
];
