/* Contenido de "PAES Biología" (Fabimath, beta) · Unidad 3 · Herencia y evolución (parte evolutiva).
   Temario oficial PAES Admisión 2027, área «Herencia y evolución»: evidencias a favor de la evolución biológica
   (anatomía comparada con estructuras homólogas y análogas, embriología, biología molecular y registro fósil),
   aportes de Lamarck, Darwin y Wallace, y fundamentos de la evolución mediante selección natural con ejemplos.
   Estilo de preguntas tomado de PAES Invierno 2026, PAES Regular 2026 y PAES Invierno 2027 (paes/biologia/fuentes/).
   Figuras TikZ en paes/biologia/tikz/evo_*.tex, compiladas a paes/biologia/fig/. Usa r (String.raw) de paes_data.js. */
const BIO_EVOLUCION = [

/* =====================================================================
   TEMA 1 · EVIDENCIAS DE LA EVOLUCIÓN
   ===================================================================== */
{
  id: 'bio_evidencias', unit: 'Unidad 3 · Herencia y evolución', icon: '🦴',
  title: 'Evidencias de la evolución',
  desc: 'Cómo sabemos que las especies evolucionan: anatomía comparada (estructuras homólogas, análogas y vestigiales), embriología, comparación de secuencias de ADN y proteínas, registro fósil y lectura de árboles filogenéticos.',
  slides: [
    { t: 'La evolución y sus evidencias', b: r`
      <div class="cols"><div>
      <p>La <b>evolución biológica</b> es el cambio en las características heredables de las <b>poblaciones</b> a lo largo de muchas generaciones. Una de sus ideas centrales es la <b>descendencia con modificación</b>: las especies actuales descienden de especies anteriores, y dos especies cualesquiera comparten, en algún momento del pasado, un <b>ancestro común</b>.</p>
      <p>Esta idea es una <b>teoría científica</b>: una explicación amplia, puesta a prueba muchas veces y respaldada por evidencias de áreas muy distintas que apuntan a la misma conclusión.</p>
      <ul><li><b>Anatomía comparada:</b> se comparan estructuras del cuerpo de especies actuales.</li>
      <li><b>Embriología comparada:</b> se compara el desarrollo de los embriones.</li>
      <li><b>Biología molecular:</b> se comparan secuencias de ADN y de proteínas.</li>
      <li><b>Registro fósil:</b> se estudian restos de organismos del pasado conservados en las rocas.</li></ul>
      </div><div>
      <div class="box"><b>La pregunta que se repite</b> En todas estas evidencias la PAES pregunta lo mismo: <b>¿qué tan emparentadas están estas especies?</b> Mientras más rasgos compartan por haberlos heredado de un ancestro (huesos, etapas del embrión, secuencias de ADN), más reciente es su ancestro común.</div>
      <div class="box"><b>Recuerda</b> Evolucionan las poblaciones, a lo largo de generaciones. Un individuo no evoluciona durante su vida: crece, aprende o se entrena, pero esos cambios no modifican el ADN de sus gametos.</div>
      </div></div>` },
    { t: 'Anatomía comparada: estructuras homólogas', b: r`
      <div class="cols"><div>
      <p>Las <b>estructuras homólogas</b> tienen el <b>mismo origen embrionario</b> y el <b>mismo plan básico</b>, aunque hoy cumplan funciones distintas.</p>
      <p>El ejemplo clásico son las extremidades anteriores de los mamíferos. El brazo humano, la pata del gato, la aleta de la ballena y el ala del murciélago sirven para tomar objetos, caminar, nadar y volar, pero todas tienen la misma secuencia de huesos: un <b>húmero</b>, luego <b>radio y cúbito</b>, luego los <b>carpos</b> y al final <b>metacarpos y falanges</b>.</p>
      <p>Lo que cambia es la forma y el largo de cada hueso: dedos muy largos que sostienen la membrana del ala en el murciélago, huesos cortos y anchos dentro de la aleta en la ballena.</p>
      <p><b>Qué indican:</b> que estas especies heredaron ese plan de un <b>ancestro común</b>. A partir de él, cada linaje se fue adaptando a ambientes distintos: es la <b>evolución divergente</b>.</p>
      </div><div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/evo_extremidades.svg" alt="Extremidades anteriores de humano, gato, ballena y murciélago, con los mismos grupos de huesos pintados del mismo color: húmero naranjo, radio y cúbito azules, carpos verdes, metacarpos y falanges lila"></div>
      </div></div>` },
    { t: 'Estructuras análogas, vestigiales y embriología', b: r`
      <div class="cols"><div>
      <p><b>Estructuras análogas.</b> Cumplen la <b>misma función</b>, pero tienen <b>distinto origen</b> y distinta estructura interna. El ala de una mariposa es una lámina sin huesos; el ala de un ave está sostenida por huesos. Otros ejemplos: el ojo del pulpo y el ojo humano, o la forma hidrodinámica del tiburón y la del delfín. Indican <b>evolución convergente</b>: ambientes o modos de vida parecidos favorecieron soluciones parecidas en linajes poco emparentados.</p>
      <p><b>Estructuras vestigiales.</b> Son estructuras <b>reducidas</b>, que no cumplen función o cumplen una función menor que en los ancestros. Ejemplos: los pequeños huesos de la cadera (pelvis) dentro del cuerpo de las ballenas, el cóccix humano y las alas diminutas del kiwi. Indican que la especie desciende de ancestros en los que esa estructura estaba desarrollada.</p>
      </div><div>
      <p><b>Embriología comparada.</b> En las primeras etapas del desarrollo, los embriones de peces, aves y mamíferos se parecen mucho: todos tienen <b>arcos y hendiduras faríngeas</b> y una <b>cola</b>. Después, cada uno sigue su camino: en los peces los arcos faríngeos originan las branquias y en los mamíferos originan partes de la mandíbula, del oído medio y del cuello. Este desarrollo compartido indica un <b>ancestro común</b> de los vertebrados.</p>
      <div class="box"><b>Recuerda</b><br>· Homólogas: mismo origen, función distinta → ancestro común (divergencia).<br>· Análogas: misma función, origen distinto → convergencia.<br>· Las alas del ave y del murciélago son homólogas como extremidades anteriores (mismos huesos), y análogas como alas: el vuelo surgió por separado en cada grupo.<br>· Las hendiduras faríngeas del embrión humano originan estructuras de la cabeza y el cuello; el ser humano respira con pulmones.</div>
      </div></div>` },
    { t: 'Biología molecular', b: r`
      <div class="cols"><div>
      <p>Todos los seres vivos usan el ADN como material genético y prácticamente el mismo <b>código genético</b>. Esa universalidad ya es una evidencia de un origen común.</p>
      <p>Además, se pueden comparar las <b>secuencias de nucleótidos</b> de un mismo gen, o las <b>secuencias de aminoácidos</b> de una misma proteína, en distintas especies. Las diferencias se acumulan con el tiempo por mutaciones. Por eso:</p>
      <div class="box"><b>Regla de lectura</b> Mientras <b>menos diferencias</b> (o más porcentaje de similitud) haya entre dos especies, <b>más reciente</b> es su ancestro común y más estrecho su parentesco.</div>
      <p><b>Ejemplo real:</b> el citocromo c, una proteína de la respiración celular, es idéntico en el ser humano y el chimpancé, y difiere en más de 40 aminoácidos entre el ser humano y la levadura.</p>
      <p>Esta evidencia es muy útil cuando la anatomía engaña: dos especies pueden verse parecidas por convergencia, pero sus secuencias revelan su parentesco real.</p>
      </div><div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/evo_secuencias.svg" alt="Fragmento de ADN de 18 bases de la especie W comparado con las especies X, Y y Z; las bases distintas están marcadas en rojo: X tiene 2 diferencias, Y tiene 1 y Z tiene 6"></div>
      <div class="box"><b>Ejemplo resuelto</b> En la figura, la especie Y difiere de W en 1 base, X en 2 y Z en 6. De mayor a menor parentesco con W: <b>Y, X, Z</b>.</div>
      </div></div>` },
    { t: 'Registro fósil', b: r`
      <div class="cols"><div>
      <p>Un <b>fósil</b> es un resto (huesos, conchas, dientes) o una huella de un organismo del pasado conservado en las rocas. La mayoría se forma en <b>rocas sedimentarias</b>, que se depositan en capas o <b>estratos</b>.</p>
      <p><b>Datación relativa.</b> Si los estratos no han sido alterados, los de abajo se depositaron primero: son <b>más antiguos</b> (principio de superposición). Así se ordenan los fósiles del más antiguo al más reciente, sin saber su edad en años.</p>
      <p><b>Datación absoluta.</b> Mide la edad en años usando isótopos radiactivos de las rocas o de los restos, como el carbono-14 para restos de hasta unos 50 000 años.</p>
      <p><b>Fósiles de transición.</b> Tienen rasgos de dos grupos. <i>Archaeopteryx</i> (unos 150 millones de años) tenía plumas y alas como un ave, y dientes, garras en las alas y una cola larga con huesos como un reptil. <i>Tiktaalik</i> (unos 375 millones de años) era un pez con cuello móvil y aletas con huesos similares a los de un brazo.</p>
      </div><div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/evo_estratos.svg" alt="Columna de cinco estratos con fósiles: trilobites abajo, amonitas en los estratos intermedios, peces más arriba y helechos y conchas en el estrato superior; una flecha indica que hacia arriba los estratos son más recientes"></div>
      <div class="box"><b>Qué responde y qué no</b> Con una columna de estratos se puede responder <b>qué especie es más antigua</b> y <b>cuáles vivieron en la misma época</b> (aparecen en el mismo estrato). No basta para saber la causa de una extinción ni quién desciende de quién.</div>
      </div></div>` },
    { t: 'Árboles filogenéticos', b: r`
      <div class="cols"><div>
      <p>Un <b>árbol filogenético</b> resume las relaciones de parentesco que se deducen de todas las evidencias. Se lee así:</p>
      <ul><li>Las <b>puntas</b> de las ramas son las especies (actuales o extintas).</li>
      <li>Cada <b>nodo</b> (punto donde se separan dos ramas) representa un <b>ancestro común</b>.</li>
      <li>Dos especies están más emparentadas mientras <b>más reciente</b> sea el nodo que comparten (más cerca de las puntas).</li></ul>
      <p>En el árbol de la figura, el lagarto y el ave comparten un ancestro más reciente que el que comparten el lagarto y el ratón. Por eso el lagarto está más emparentado con el ave que con el ratón, aunque a simple vista se parezca más al ratón (cuatro patas, sin plumas).</p>
      </div><div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/evo_arbol.svg" alt="Árbol filogenético con pez, rana, ratón, lagarto y ave; primero se separa el pez, luego la rana, luego el ratón, y lagarto y ave son las especies más emparentadas"></div>
      <div class="box"><b>Recuerda</b><br>· Lo que importa son los nodos, no el orden vertical de los nombres: girar las ramas en un nodo no cambia el árbol.<br>· Las especies actuales no descienden unas de otras: comparten ancestros. El ser humano y el chimpancé comparten un ancestro común.</div>
      </div></div>` },
    { t: 'Lo clave del tema', b: r`
      <table><thead><tr><th>Evidencia</th><th>Qué se compara</th><th>Qué indica</th><th>Ejemplo</th></tr></thead><tbody>
      <tr><td>Estructuras homólogas</td><td>mismo origen y plan, distinta función</td><td>ancestro común (divergencia)</td><td>brazo, aleta de ballena, ala de murciélago</td></tr>
      <tr><td>Estructuras análogas</td><td>misma función, distinto origen</td><td>convergencia, no parentesco cercano</td><td>ala de mariposa y ala de ave</td></tr>
      <tr><td>Estructuras vestigiales</td><td>estructuras reducidas</td><td>ancestros con la estructura desarrollada</td><td>pelvis de ballena, cóccix</td></tr>
      <tr><td>Embriología</td><td>etapas tempranas del desarrollo</td><td>ancestro común</td><td>arcos faríngeos y cola en vertebrados</td></tr>
      <tr><td>Biología molecular</td><td>secuencias de ADN o de aminoácidos</td><td>menos diferencias = parentesco más cercano</td><td>citocromo c</td></tr>
      <tr><td>Registro fósil</td><td>fósiles en estratos</td><td>orden de aparición, formas de transición</td><td><i>Archaeopteryx</i>, <i>Tiktaalik</i></td></tr></tbody></table>
      <div class="box" style="margin-top:14px"><b>Recuerda</b><br>· Solo las estructuras homólogas indican parentesco; las análogas indican ambientes parecidos.<br>· En estratos no alterados, más abajo es más antiguo.<br>· Una tabla de diferencias o de similitud indica parentesco, no qué especie apareció primero.<br>· En un árbol, el parentesco lo da el nodo compartido más reciente.</div>
      <div class="box" style="margin-top:14px"><b>Método PAES</b> 1. Identifica la evidencia (anatomía, embrión, secuencia, fósil). 2. Pregúntate qué permite concluir esa evidencia y qué no (parentesco, orden de antigüedad, causa). 3. En tablas, busca la menor diferencia o la mayor similitud. 4. En árboles, busca el nodo más reciente que une a las especies. 5. Descarta las alternativas que van más allá de los datos.</div>` }
  ],
  example: {
    src: 'PAES Regular 2026, adaptada',
    enun: r`<p>Un equipo de investigación secuenció el mismo fragmento de un gen en cuatro especies de anfibios, W, X, Y y Z. La figura muestra las secuencias alineadas; en rojo están las bases que difieren de las de la especie W en la misma posición.</p><p>A partir de estos datos, ¿cuál de las siguientes opciones ordena las especies X, Y y Z de <b>mayor a menor</b> parentesco con la especie W?</p>`,
    fig: { type: 'img', src: 'paes/biologia/fig/evo_secuencias.svg', alt: 'Secuencia de 18 bases de la especie W: ATGGCATTCGGACTAGCT. Especie X: 2 bases distintas. Especie Y: 1 base distinta. Especie Z: 6 bases distintas' },
    alts: ['X, Y, Z', 'Z, X, Y', 'Y, X, Z', 'Y, Z, X'], ok: 2,
    sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Ordenar las especies según su parentesco con W, usando la comparación de secuencias de ADN.</p><p><b>Paso 2. Cuenta las diferencias.</b> Recorre cada secuencia y cuenta las bases marcadas: X tiene 2 (posiciones 6 y 15), Y tiene 1 (posición 18) y Z tiene 6.</p><p><b>Paso 3. Aplica la regla.</b> Las diferencias se acumulan con el tiempo desde que dos linajes se separaron. Menos diferencias significa un ancestro común más reciente, es decir, un parentesco más cercano.</p><p><b>Respuesta:</b> Y (1 diferencia), X (2) y Z (6).</p><p><b>¿Por qué no las otras?</b> «X, Y, Z» pone primero a X, que tiene más diferencias que Y. «Z, X, Y» invierte la regla: ordena de menor a mayor parentesco. «Y, Z, X» pone a Z antes que X, aunque Z tiene 6 diferencias y X solo 2.</p>`,
    conc: 'Menos diferencias en la secuencia = ancestro común más reciente = parentesco más cercano.'
  },
  bank: [
    /* Tipo 1: estructuras homólogas, análogas y vestigiales (temario; anatomía comparada) */
    { enun: r`<p>La figura muestra, de forma simplificada, los huesos de las extremidades anteriores de cuatro mamíferos. Los huesos pintados del mismo color ocupan la misma posición en las cuatro extremidades.</p><p>¿Qué conclusión apoya esta evidencia?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/evo_extremidades.svg', alt: 'Extremidades anteriores de humano, gato, ballena y murciélago: todas tienen húmero, radio y cúbito, carpos, y metacarpos y falanges, con formas y largos distintos' },
      alts: ['Las cuatro especies descienden de un ancestro común que tenía ese mismo plan de huesos.', 'Las cuatro extremidades son estructuras análogas, porque cumplen funciones distintas.', 'Cada especie formó estos huesos durante su vida, según el uso que les dio.', 'La ballena está más emparentada con los peces que con el murciélago, porque ambos nadan.'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Qué permite concluir que cuatro extremidades con funciones distintas tengan los mismos huesos en el mismo orden.</p><p><b>Paso 2. Clasifica las estructuras.</b> Mismo plan óseo y mismo origen, con funciones distintas (tomar, caminar, nadar, volar): son <b>estructuras homólogas</b>.</p><p><b>Paso 3. Interpreta.</b> Las estructuras homólogas se explican porque las especies heredaron ese plan de un ancestro común; después, cada linaje lo modificó según su modo de vida.</p><p><b>Respuesta:</b> las cuatro especies descienden de un ancestro común con ese plan de huesos.</p><p><b>¿Por qué no las otras?</b> Las estructuras análogas tienen la misma función y distinto origen; aquí ocurre lo contrario. Los huesos no se forman por el uso durante la vida: están determinados por el desarrollo embrionario, que se hereda. Que la ballena y los peces naden es una semejanza de función; la aleta de la ballena tiene los huesos de un mamífero, lo que la acerca al murciélago y no a los peces.</p>`, conc: 'Mismos huesos con funciones distintas = estructuras homólogas = ancestro común.' },
    { enun: r`<p>Tanto la mariposa como la golondrina vuelan con alas. El ala de la golondrina está sostenida por huesos y cubierta de plumas; el ala de la mariposa es una lámina delgada de cutícula, sin huesos.</p><p>¿Cómo se clasifican estas alas y qué indican?</p>`, src: 'Estilo PAES',
      alts: ['Son homólogas e indican un ancestro común reciente.', 'Son análogas e indican que el vuelo surgió de forma independiente en ambos grupos.', 'Son vestigiales e indican que ambas especies están perdiendo la capacidad de volar.', 'Son homólogas e indican evolución convergente.'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Clasificar dos estructuras que cumplen la misma función con estructura interna distinta.</p><p><b>Paso 2. Compara origen y función.</b> Misma función (volar), pero origen y estructura diferentes (huesos y plumas frente a una lámina de cutícula): son <b>estructuras análogas</b>.</p><p><b>Paso 3. Interpreta.</b> Las estructuras análogas no indican parentesco cercano. Indican <b>evolución convergente</b>: la capacidad de volar apareció por separado en los insectos y en las aves.</p><p><b>Respuesta:</b> son análogas e indican que el vuelo surgió de forma independiente.</p><p><b>¿Por qué no las otras?</b> Para ser homólogas deberían tener el mismo origen y plan, y no lo tienen. Las estructuras vestigiales son reducidas y sin función, y ambas alas sirven para volar. La evolución convergente se asocia a estructuras análogas, no a homólogas.</p>`, conc: 'Misma función, distinto origen: estructuras análogas, evolución convergente.' },
    { enun: r`<p>En el interior del cuerpo de algunas especies de ballenas hay pequeños huesos de cadera (pelvis) que no están unidos a la columna vertebral ni sostienen patas.</p><p>¿Cuál de las siguientes interpretaciones es correcta?</p>`, src: 'Estilo PAES',
      alts: ['Son estructuras análogas a las aletas de los peces.', 'Se formaron porque las ballenas dejaron de usar las patas y esa pérdida se heredó.', 'Indican que las ballenas están evolucionando para volver a caminar.', 'Son estructuras vestigiales que indican que las ballenas descienden de ancestros con patas traseras.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Interpretar una estructura reducida que ya no cumple su función original.</p><p><b>Paso 2. Clasifica.</b> Una pelvis pequeña que no sostiene patas es una <b>estructura vestigial</b>: una estructura reducida respecto de la de sus ancestros.</p><p><b>Paso 3. Interpreta.</b> Las estructuras vestigiales indican que la especie desciende de ancestros en los que esa estructura estaba desarrollada. El registro fósil lo confirma: hay fósiles de cetáceos antiguos con patas traseras.</p><p><b>Respuesta:</b> son estructuras vestigiales que indican ancestros con patas traseras.</p><p><b>¿Por qué no las otras?</b> Una pelvis y una aleta no cumplen la misma función, así que no son análogas. Explicar la reducción por el desuso y su herencia es la idea de Lamarck: los cambios por uso o desuso durante la vida no se heredan. La evolución no tiene una meta: nada indica que las ballenas vayan a volver a caminar.</p>`, conc: 'Estructura reducida sin su función original: vestigial, huella de los ancestros.' },
    { enun: r`<p>Un estudiante debe elegir un par de estructuras que sirva como evidencia de parentesco evolutivo entre dos especies.</p><p>¿Cuál de los siguientes pares corresponde a estructuras homólogas?</p>`, src: 'Estilo PAES',
      alts: ['El ala de una abeja y el ala de un murciélago.', 'La forma hidrodinámica de un tiburón y la de un delfín.', 'El brazo de un ser humano y la aleta pectoral de un delfín.', 'El ojo de un pulpo y el ojo de un ser humano.'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Un par de estructuras con el mismo origen y el mismo plan básico, aunque su función sea distinta.</p><p><b>Paso 2. Revisa cada par.</b> El brazo humano y la aleta pectoral del delfín tienen húmero, radio, cúbito, carpos y falanges: mismo plan, distinta función (tomar objetos, nadar). Son <b>homólogas</b>.</p><p><b>Respuesta:</b> el brazo humano y la aleta pectoral del delfín.</p><p><b>¿Por qué no las otras?</b> El ala de la abeja no tiene huesos; la del murciélago sí: misma función, distinto origen, son análogas. La forma hidrodinámica del tiburón (un pez) y la del delfín (un mamífero) es convergencia por nadar en el agua. El ojo del pulpo y el humano se formaron por caminos distintos: también son análogos.</p>`, conc: 'Homólogas: mismo plan de huesos aunque la función cambie.' },

    /* Tipo 2: embriología comparada y variables de investigación (Invierno 2026 n.º 14) */
    { enun: r`<p>Para obtener evidencia embriológica del parentesco entre dos especies de anfibios, 1 y 2, que viven en lagunas separadas por una cordillera, un equipo examina embriones de ambas especies. En cada embrión registra el día del desarrollo en que aparece una estructura Y, que en las dos especies se origina del mismo grupo de células.</p><p>¿Cuáles son las variables de esta investigación?</p>`, src: 'PAES Invierno 2026, adaptada',
      alts: ['Independiente: el grado de parentesco. Dependiente: el día en que aparece la estructura Y.', 'Independiente: la altura de la cordillera. Dependiente: el grado de parentesco.', 'Independiente: el día en que aparece la estructura Y. Dependiente: la especie de anfibio.', 'Independiente: la especie de anfibio (1 o 2). Dependiente: el día en que aparece la estructura Y.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Identificar qué compara el equipo (variable independiente) y qué mide (variable dependiente).</p><p><b>Paso 2. ¿Qué se compara?</b> Los embriones de la especie 1 con los de la especie 2. La especie es lo que el equipo elige y distingue entre los grupos: es la <b>variable independiente</b>.</p><p><b>Paso 3. ¿Qué se mide?</b> El día del desarrollo en que aparece la estructura Y en cada embrión: es la <b>variable dependiente</b>.</p><p><b>Respuesta:</b> independiente, la especie; dependiente, el día en que aparece Y.</p><p><b>¿Por qué no las otras?</b> El grado de parentesco es lo que se quiere inferir al final, a partir de los resultados; no se mide directamente en el experimento. La altura de la cordillera no se varía ni se mide. Poner el día de aparición como independiente invierte las variables: ese dato depende de la especie, no al revés.</p>`, conc: 'Independiente: lo que se compara (la especie). Dependiente: lo que se mide (el día de aparición).' },
    { enun: r`<p>En las primeras etapas del desarrollo, los embriones de un pez, de un pollo y de un ser humano presentan arcos y hendiduras faríngeas y una cola. En el pez, los arcos faríngeos originan las branquias; en el ser humano, originan partes de la mandíbula, del oído medio y del cuello.</p><p>¿Qué apoya esta observación?</p>`, src: 'Estilo PAES',
      alts: ['Que estos vertebrados comparten un ancestro común.', 'Que el ser humano respira por branquias durante su desarrollo.', 'Que el pez es el ancestro directo del pollo y del ser humano.', 'Que estas estructuras son análogas, porque en los adultos cumplen funciones distintas.'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Qué concluir de que embriones de especies distintas compartan estructuras en sus primeras etapas.</p><p><b>Paso 2. Interpreta.</b> Estructuras con el mismo origen embrionario que luego dan órganos distintos son homólogas. Que tres vertebrados tan distintos compartan ese programa de desarrollo se explica porque lo heredaron de un <b>ancestro común</b>.</p><p><b>Respuesta:</b> apoya que estos vertebrados comparten un ancestro común.</p><p><b>¿Por qué no las otras?</b> En el ser humano los arcos faríngeos originan estructuras de la cabeza y el cuello, no branquias; el embrión recibe oxígeno a través de la placenta. Los peces actuales no son ancestros de las aves ni de los mamíferos: comparten con ellos un ancestro. Estructuras de igual origen y distinta función adulta son homólogas, no análogas.</p>`, conc: 'Embriones parecidos en etapas tempranas: ancestro común.' },

    /* Tipo 3: biología molecular, tablas de diferencias y de similitud (Invierno 2026 n.º 69, Regular 2026 n.º 15, Invierno 2027 n.º 73) */
    { enun: r`<p>La tabla muestra el número de aminoácidos distintos en la proteína citocromo c de cuatro especies, en comparación con la de la especie M.</p><p>¿Qué conclusión es correcta?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/evo_tabla_aa.svg', alt: 'Tabla de aminoácidos distintos en el citocromo c respecto de la especie M: especie 1, 14; especie 2, 2; especie 3, 27; especie 4, 8' },
      alts: ['La especie 3 es la más emparentada con M, porque tiene más aminoácidos distintos.', 'La especie 2 comparte con M un ancestro común más reciente que el que comparte la especie 4 con M.', 'La especie 1 es el ancestro de la especie 3.', 'La especie 4 apareció antes que la especie 1.'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Una conclusión que se pueda sacar de una tabla de diferencias en una proteína.</p><p><b>Paso 2. Aplica la regla.</b> Menos diferencias significa un ancestro común más reciente. De más a menos emparentada con M: especie 2 (2), especie 4 (8), especie 1 (14) y especie 3 (27).</p><p><b>Paso 3. Compara 2 y 4.</b> La especie 2 tiene menos diferencias con M que la 4, así que comparte con M un ancestro más reciente.</p><p><b>Respuesta:</b> la especie 2 comparte con M un ancestro común más reciente que la especie 4.</p><p><b>¿Por qué no las otras?</b> Más diferencias indican menos parentesco, así que la especie 3 es la menos emparentada. La tabla compara cada especie con M; no dice quién desciende de quién. Tampoco indica cuándo apareció cada especie: todas son especies que comparamos hoy.</p>`, conc: 'La tabla de diferencias informa el parentesco, no el orden de aparición.' },
    { enun: r`<p>Un grupo de investigación comparó la secuencia de aminoácidos de la hemoglobina de tres especies de roedores: la especie R, que vive sobre los 4000 m de altitud en el altiplano, y las especies S y T, que viven cerca del nivel del mar. La menor diferencia se encontró entre S y T; además, R tiene menos diferencias con S que con T.</p><p>¿Para qué sirve principalmente esta información?</p>`, src: 'PAES Invierno 2026, adaptada',
      alts: ['Para conocer el orden en que aparecieron las tres especies.', 'Para demostrar que las tres especies tienen estructuras análogas.', 'Para saber cuál de las especies resiste mejor el frío.', 'Para inferir las relaciones de parentesco entre las tres especies.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> La utilidad de comparar la secuencia de una proteína entre especies.</p><p><b>Paso 2. Recuerda qué mide.</b> La cantidad de diferencias en una misma proteína indica qué tan reciente es el ancestro común: es una evidencia de <b>parentesco</b>. Con estos datos, S y T son las más emparentadas, y R está más cerca de S que de T.</p><p><b>Respuesta:</b> sirve para inferir las relaciones de parentesco entre las tres especies.</p><p><b>¿Por qué no las otras?</b> Las tres especies existen hoy; las diferencias indican cuán emparentadas están, no cuál apareció primero. Las estructuras análogas se estudian con la anatomía, y una misma proteína presente en las tres especies, de origen común, es una molécula homóloga. La resistencia al frío no se mide en este estudio.</p>`, conc: 'Comparar secuencias de una proteína sirve para inferir parentesco.' },
    { enun: r`<p>En un bosque del sur de Chile se descubrió una especie de escarabajo, N. Un equipo quiere saber, de la forma más directa, con cuál de cuatro especies conocidas de escarabajos está más estrechamente emparentada.</p><p>¿Qué debería analizar el equipo?</p>`, src: 'PAES Invierno 2027, adaptada',
      alts: ['El tamaño corporal promedio de los individuos de las cinco especies.', 'La cantidad de alimento que consume en un día cada una de las cinco especies.', 'La secuencia de nucleótidos de un mismo gen presente en las cinco especies.', 'El color del caparazón de los individuos de las cinco especies.'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El dato más directo para determinar parentesco evolutivo.</p><p><b>Paso 2. Elige la evidencia.</b> Comparar la secuencia de un mismo gen en las cinco especies permite contar las diferencias entre N y cada especie conocida. La especie con menos diferencias es la más emparentada.</p><p><b>Respuesta:</b> la secuencia de nucleótidos de un mismo gen en las cinco especies.</p><p><b>¿Por qué no las otras?</b> El tamaño y el color pueden parecerse por vivir en ambientes similares (convergencia), sin que haya parentesco cercano. La cantidad de alimento consumido depende del ambiente y de la actividad del individuo, no del parentesco.</p>`, conc: 'Para medir parentesco, compara secuencias de un mismo gen o proteína.' },
    { enun: r`<p>En una cueva de la Patagonia se halló el hueso de un mamífero extinto. Se extrajo ADN del fósil y se comparó un mismo fragmento con el de cuatro especies actuales. Los resultados fueron:</p><table><thead><tr><th>Especie actual</th><th>Similitud con el fósil (%)</th></tr></thead><tbody><tr><td>1</td><td>62</td></tr><tr><td>2</td><td>97</td></tr><tr><td>3</td><td>58</td></tr><tr><td>4</td><td>71</td></tr></tbody></table><p>¿Cuál de las siguientes conclusiones es correcta?</p>`, src: 'PAES Regular 2026, adaptada',
      alts: ['El fósil pertenece a una especie estrechamente emparentada con la especie 2.', 'El fósil pertenece a una especie sin relación evolutiva con las especies comparadas.', 'El fósil pertenece al ancestro directo de la especie 3.', 'La especie 4 es la más emparentada con el fósil, porque su similitud es intermedia.'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Interpretar porcentajes de similitud entre secuencias de ADN.</p><p><b>Paso 2. Aplica la regla.</b> Más similitud significa un ancestro común más reciente. La especie 2 tiene 97 % de similitud, mucho más que las demás.</p><p><b>Respuesta:</b> el fósil pertenece a una especie estrechamente emparentada con la especie 2.</p><p><b>¿Por qué no las otras?</b> Todas las especies tienen similitudes altas, de 58 % o más: hay relación evolutiva con todas, aunque con distinta cercanía. La especie 3 tiene la menor similitud, así que es la menos emparentada, y la tabla no permite afirmar que sea descendiente directa del fósil. El parentesco más cercano lo da la mayor similitud, no un valor intermedio.</p>`, conc: 'Mayor similitud de secuencia = parentesco más cercano.' },

    /* Tipo 4: registro fósil y estratos (Invierno 2026 n.º 15) */
    { enun: r`<p>Una geóloga estudia una columna de estratos de roca sedimentaria que no ha sido alterada desde su formación. En cada estrato registra los fósiles de especies extintas, P, Q, R, S y T, como muestra la figura.</p><p>¿Qué pregunta de investigación se puede responder directamente con estos resultados?</p>`, src: 'PAES Invierno 2026, adaptada',
      fig: { type: 'img', src: 'paes/biologia/fig/evo_estratos_q.svg', alt: 'Columna de cinco estratos, del I arriba al V abajo. Estrato V: P. Estrato IV: P y Q. Estrato III: Q y R. Estrato II: R y S. Estrato I: S y T' },
      alts: ['¿Cuál de las especies P, Q, R, S y T es la más antigua y cuál la más reciente?', '¿Por qué se extinguió la especie P?', '¿Cuál de estas especies estaría mejor adaptada al clima actual?', '¿Qué condiciones del ambiente favorecieron la fosilización de la especie R?'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Una pregunta que se responda solo con la ubicación de los fósiles en los estratos.</p><p><b>Paso 2. Usa la superposición.</b> En estratos no alterados, los de abajo son más antiguos. P aparece en el estrato V, el más profundo: es la especie más antigua. T aparece solo en el estrato I, el superior: es la más reciente.</p><p><b>Respuesta:</b> ¿cuál de las especies es la más antigua y cuál la más reciente?</p><p><b>¿Por qué no las otras?</b> La figura muestra dónde están los fósiles, pero no la causa de una extinción. Para saber si una especie extinta estaría adaptada al clima actual habría que conocer sus características y las del ambiente actual. Las condiciones de fosilización requieren estudiar el tipo de roca y del ambiente de depósito, datos que no se registraron.</p>`, conc: 'Una columna de estratos permite ordenar las especies por antigüedad.' },
    { enun: r`<p>La figura muestra los fósiles de las especies extintas P, Q, R, S y T encontrados en una columna de estratos que no ha sido alterada.</p><p>¿Qué conclusión se puede obtener a partir de estos datos?</p>`, src: 'PAES Invierno 2026, adaptada',
      fig: { type: 'img', src: 'paes/biologia/fig/evo_estratos_q.svg', alt: 'Columna de cinco estratos, del I arriba al V abajo. Estrato V: P. Estrato IV: P y Q. Estrato III: Q y R. Estrato II: R y S. Estrato I: S y T' },
      alts: ['La especie T desciende de la especie S.', 'Las especies Q y R vivieron en una misma época.', 'La especie R es más antigua que la especie Q.', 'La especie P se extinguió porque apareció la especie Q.'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Una conclusión que se apoye solo en la posición de los fósiles.</p><p><b>Paso 2. Busca especies en un mismo estrato.</b> Q y R aparecen juntas en el estrato III, que se depositó en un mismo período. Entonces vivieron en una misma época.</p><p><b>Respuesta:</b> las especies Q y R vivieron en una misma época.</p><p><b>¿Por qué no las otras?</b> Que S aparezca antes que T no prueba que T descienda de S; para eso harían falta otras evidencias, como rasgos homólogos. Q aparece ya en el estrato IV y R recién en el III, así que Q es más antigua que R. P y Q coexistieron en el estrato IV, pero la columna no informa la causa de la extinción de P.</p>`, conc: 'Fósiles en un mismo estrato: especies de una misma época.' },
    { enun: r`<p><i>Tiktaalik</i> es un fósil de unos 375 millones de años. Tenía escamas, aletas y branquias como un pez, pero también cuello móvil, costillas robustas y aletas con huesos similares al húmero, al radio y al cúbito de los tetrápodos (vertebrados de cuatro extremidades).</p><p>¿Por qué este fósil es una evidencia de la evolución?</p>`, src: 'Estilo PAES',
      alts: ['Porque demuestra que los peces actuales se transformarán en anfibios.', 'Porque es una estructura vestigial de los anfibios actuales.', 'Porque prueba que los caracteres que un pez adquiere al salir del agua se heredan.', 'Porque es una forma de transición con rasgos de peces y de tetrápodos, lo que apoya que los tetrápodos evolucionaron a partir de peces.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El valor de un fósil que combina rasgos de dos grupos.</p><p><b>Paso 2. Reconoce el tipo de fósil.</b> Un organismo con rasgos de peces (escamas, branquias, aletas) y de tetrápodos (cuello, huesos de extremidad) es un <b>fósil de transición</b>.</p><p><b>Paso 3. Interpreta.</b> Los fósiles de transición muestran formas intermedias entre grupos, como predice la descendencia con modificación: apoyan que los tetrápodos surgieron a partir de un linaje de peces.</p><p><b>Respuesta:</b> es una forma de transición que apoya que los tetrápodos evolucionaron a partir de peces.</p><p><b>¿Por qué no las otras?</b> La evolución no tiene una dirección prefijada: los peces actuales son especies actuales, no etapas hacia otro grupo. Un fósil es un organismo completo, no una estructura reducida de otra especie. La herencia de caracteres adquiridos es la idea de Lamarck y no está respaldada por la evidencia.</p>`, conc: 'Un fósil de transición tiene rasgos de dos grupos y muestra cómo uno surgió del otro.' },

    /* Tipo 5: lectura de árboles filogenéticos */
    { enun: r`<p>El siguiente árbol filogenético representa las relaciones de parentesco entre cinco especies, A, B, C, D y E. Los nodos están numerados del 1 al 4.</p><p>¿Qué nodo representa el ancestro común más reciente de las especies A y C?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/evo_arbol_q.svg', alt: 'Árbol filogenético: el nodo 1 es la raíz y se divide en el nodo 2 y el nodo 4. Del nodo 2 salen la especie A y el nodo 3; del nodo 3 salen las especies B y C. Del nodo 4 salen las especies D y E' },
      alts: ['Nodo 1', 'Nodo 2', 'Nodo 3', 'Nodo 4'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El punto más reciente del árbol del que descienden tanto A como C.</p><p><b>Paso 2. Recorre las ramas hacia atrás.</b> Desde C se baja al nodo 3, que también lleva a B, pero no a A. Se sigue al nodo 2, del que salen A y el nodo 3: ahí se juntan A y C.</p><p><b>Respuesta:</b> el nodo 2.</p><p><b>¿Por qué no las otras?</b> El nodo 1 es ancestro de A y C, pero también de todas las especies: no es el más reciente. El nodo 3 es el ancestro común de B y C; A no sale de él. El nodo 4 solo lleva a D y E.</p>`, conc: 'El ancestro común más reciente es el primer nodo donde se juntan las dos ramas.' },
    { enun: r`<p>Observa el árbol filogenético de las especies A, B, C, D y E.</p><p>¿Cuál de las siguientes afirmaciones es correcta?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/evo_arbol_q.svg', alt: 'Árbol filogenético: el nodo 1 es la raíz y se divide en el nodo 2 y el nodo 4. Del nodo 2 salen la especie A y el nodo 3; del nodo 3 salen las especies B y C. Del nodo 4 salen las especies D y E' },
      alts: ['La especie A está más emparentada con B que con C.', 'La especie D es el ancestro de la especie E.', 'La especie C está más emparentada con A que con D.', 'La especie E está más emparentada con C que con D.'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Comparar parentescos usando los nodos que comparten las especies.</p><p><b>Paso 2. Busca los nodos.</b> C y A se juntan en el nodo 2. C y D se juntan recién en el nodo 1, más antiguo. Entonces C comparte con A un ancestro más reciente que con D.</p><p><b>Respuesta:</b> la especie C está más emparentada con A que con D.</p><p><b>¿Por qué no las otras?</b> A se junta con B y con C en el mismo nodo 2: está igual de emparentada con ambas. D y E son especies en las puntas del árbol; comparten el ancestro del nodo 4, pero ninguna es ancestro de la otra. E se junta con D en el nodo 4 y con C recién en el nodo 1: está más emparentada con D.</p>`, conc: 'Más emparentadas son las especies que comparten el nodo más reciente.' }
  ]
},

/* =====================================================================
   TEMA 2 · LAMARCK, DARWIN, WALLACE Y LA SELECCIÓN NATURAL
   ===================================================================== */
{
  id: 'bio_seleccion', unit: 'Unidad 3 · Herencia y evolución', icon: '🦒',
  title: 'Lamarck, Darwin, Wallace y la selección natural',
  desc: 'Las ideas de Lamarck y por qué se descartan, los aportes de Darwin y Wallace, los fundamentos de la selección natural y sus ejemplos (polilla moteada, resistencia a antibióticos y pesticidas, pinzones), y la lectura de gráficos de frecuencia a lo largo de generaciones.',
  slides: [
    { t: 'Lamarck: la primera teoría de la evolución', b: r`
      <div class="cols"><div>
      <p>Hasta el siglo XVIII predominaba el <b>fijismo</b>: la idea de que las especies no cambian. En 1809, el naturalista francés <b>Jean-Baptiste Lamarck</b> publicó <i>Filosofía zoológica</i>, con la primera teoría de la evolución que proponía un mecanismo. Sus ideas principales:</p>
      <ul><li><b>Uso y desuso:</b> los órganos que se usan mucho se desarrollan y los que no se usan se atrofian.</li>
      <li><b>Herencia de los caracteres adquiridos:</b> esos cambios, logrados durante la vida, se transmiten a la descendencia.</li>
      <li>Los organismos cambian en respuesta a las <b>necesidades</b> que les impone el ambiente.</li></ul>
      <p>Su ejemplo más citado: las jirafas habrían estirado el cuello para alcanzar las hojas altas, y sus crías habrían nacido con el cuello algo más largo.</p>
      </div><div>
      <div class="box"><b>Por qué se descartó</b> Los cambios que un organismo adquiere durante su vida (músculos entrenados, una cola cortada, un idioma aprendido) no modifican el ADN de sus <b>gametos</b>, y por eso no se heredan. A fines del siglo XIX, August Weismann cortó la cola de ratones durante varias generaciones y todas las crías nacieron con cola normal.</div>
      <div class="box"><b>Su mérito</b> Lamarck fue de los primeros en sostener que las especies cambian a lo largo del tiempo y que ese cambio se relaciona con el ambiente. Darwin reconoció su aporte.</div>
      </div></div>` },
    { t: 'Darwin y Wallace', b: r`
      <div class="cols"><div>
      <p><b>Charles Darwin</b> viajó alrededor del mundo en el barco <i>Beagle</i> (1831-1836), con largas estadías en Sudamérica, incluido Chile, y una visita a las islas Galápagos. Allí notó que especies muy parecidas, como los pinzones y las tortugas, variaban de una isla a otra.</p>
      <p>Al volver, reunió más evidencias: la <b>selección artificial</b> que hacen los criadores de palomas y ganado, y las ideas de Malthus sobre poblaciones que crecen más rápido que sus recursos.</p>
      <p><b>Alfred Russel Wallace</b>, estudiando la fauna del Amazonas y del archipiélago malayo, llegó por su cuenta a la misma explicación. En 1858 le envió a Darwin un ensayo con la idea, y ese mismo año se presentaron juntos los trabajos de ambos en la Sociedad Linneana de Londres.</p>
      <p>En 1859 Darwin publicó <i>El origen de las especies</i>, con abundantes evidencias de la <b>evolución por selección natural</b>.</p>
      </div><div>
      <div class="box"><b>Qué aportó cada uno</b><br>· <b>Darwin:</b> la teoría de la descendencia con modificación y de la selección natural, sostenida con una enorme cantidad de evidencias.<br>· <b>Wallace:</b> llegó de forma independiente a la selección natural y estudió la distribución geográfica de las especies (biogeografía).</div>
      <div class="box"><b>Recuerda</b> Darwin y Wallace no conocían los genes. Durante el siglo XX, la genética explicó el origen de la variación (mutaciones y recombinación) y se unió a la selección natural en la <b>teoría sintética</b> de la evolución.</div>
      </div></div>` },
    { t: 'Fundamentos de la selección natural', b: r`
      <div class="cols"><div>
      <p>La selección natural se apoya en cuatro hechos observables:</p>
      <ol><li><b>Variación heredable.</b> Los individuos de una población difieren en sus características, y parte de esas diferencias se heredan.</li>
      <li><b>Sobreproducción.</b> Nacen más individuos de los que el ambiente puede sostener.</li>
      <li><b>Lucha por la existencia.</b> Los recursos son limitados: los individuos compiten por alimento, espacio o pareja, y enfrentan depredadores y enfermedades.</li>
      <li><b>Supervivencia y reproducción diferencial.</b> Los individuos con características más favorables en ese ambiente sobreviven y dejan <b>más descendencia</b>.</li></ol>
      <p><b>Resultado:</b> a lo largo de generaciones aumenta en la población la frecuencia de las características favorables. Así se forman las <b>adaptaciones</b>.</p>
      </div><div>
      <div class="box"><b>Adaptación</b> Característica heredable que aumenta la supervivencia o la reproducción de un individuo en un ambiente determinado. Lo que cuenta es el <b>éxito reproductivo</b>: un rasgo que atrae más parejas también es adaptativo.</div>
      <div class="box"><b>Recuerda</b><br>· La variación existe <b>antes</b> del cambio ambiental; surge al azar por mutaciones y recombinación.<br>· El ambiente <b>selecciona</b> entre variantes que ya existen.<br>· La selección actúa sobre individuos, y lo que cambia es la frecuencia de las características en la <b>población</b>.</div>
      </div></div>` },
    { t: 'Lamarck y Darwin frente a frente', b: r`
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/evo_jirafas.svg" alt="Arriba, explicación de Lamarck: una jirafa estira el cuello para alcanzar las hojas, su cuello se alarga por el uso y su cría hereda el cuello alargado. Abajo, explicación de Darwin y Wallace: en la población hay jirafas de cuello corto y largo, con pocas hojas bajas sobreviven y se reproducen más las de cuello largo, y en la generación siguiente predomina el cuello largo"></div>
      <table><thead><tr><th></th><th>Lamarck</th><th>Darwin y Wallace</th></tr></thead><tbody>
      <tr><td>Origen de la variación</td><td>surge durante la vida, por el uso y la necesidad</td><td>ya existe en la población y es heredable</td></tr>
      <tr><td>Papel del ambiente</td><td>provoca el cambio en cada individuo</td><td>selecciona a los individuos mejor adaptados</td></tr>
      <tr><td>Qué cambia</td><td>cada individuo, durante su vida</td><td>la población, a lo largo de generaciones</td></tr></tbody></table>
      <div class="box" style="margin-top:14px"><b>Cómo reconocer cada explicación</b> Una explicación es <b>lamarckista</b> cuando dice que el organismo cambió <b>porque lo necesitaba</b>, <b>por el uso o el desuso</b>, o que <b>heredó algo que adquirió</b> durante su vida. Una explicación es <b>darwinista</b> cuando parte de una <b>variación previa</b> y habla de <b>supervivencia y reproducción diferencial</b> en la población.</div>` },
    { t: 'Ejemplos: polilla moteada y pinzones', b: r`
      <div class="cols"><div>
      <p><b>Polilla moteada</b> (<i>Biston betularia</i>). En Inglaterra hay polillas claras y oscuras; el color es heredable. Antes de la Revolución Industrial, los troncos estaban cubiertos de líquenes claros y casi todas las polillas eran claras. El hollín de las fábricas oscureció los troncos: las polillas oscuras quedaron mejor camufladas frente a las aves que las cazan, sobrevivieron y se reprodujeron más, y llegaron a ser la gran mayoría. Cuando las leyes redujeron la contaminación, los troncos se aclararon y la tendencia se invirtió.</p>
      <p><b>Pinzones de Galápagos.</b> Las distintas especies descienden de un ancestro que llegó desde el continente; sus picos se diversificaron según el alimento de cada ambiente. Peter y Rosemary Grant lo midieron en la isla Daphne Mayor: tras la sequía de 1977 quedaron sobre todo semillas grandes y duras, sobrevivieron más los pinzones de pico más grande y profundo, y la generación siguiente tuvo, en promedio, picos más profundos.</p>
      </div><div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/evo_polilla.svg" alt="Gráfico de porcentaje de polillas oscuras entre 1850 y 2000: sube de cerca de 2 % a 95 % hacia 1895, se mantiene alto hasta mediados del siglo XX y baja a cerca de 10 % en 2000, después de la ley de aire limpio de 1956"></div>
      <div class="box"><b>Cómo leer un gráfico de frecuencias</b> 1. Mira qué característica se mide y en qué unidad (% de la población). 2. Ubica cuándo cambia el ambiente. 3. Describe la tendencia después del cambio: si una variante aumenta generación tras generación, el ambiente la está favoreciendo.</div>
      </div></div>` },
    { t: 'Ejemplos: resistencia a antibióticos y pesticidas', b: r`
      <div class="cols"><div>
      <p>En una población de bacterias hay variación: por <b>mutaciones al azar</b>, o por genes recibidos de otras bacterias, algunas pocas son resistentes a un antibiótico antes de que se use.</p>
      <ol><li>Al aplicar el antibiótico, mueren las bacterias sensibles. El antibiótico actúa como <b>presión de selección</b>.</li>
      <li>Las resistentes sobreviven y se reproducen, con poca competencia.</li>
      <li>Tras varias generaciones, casi toda la población es resistente.</li></ol>
      <p>Lo mismo ocurre con los <b>insectos y los pesticidas</b>, y con las malezas y los herbicidas: el producto elimina a los sensibles y deja a los que ya eran resistentes.</p>
      <p>Por eso los antibióticos se usan solo con receta, nunca contra virus (como el resfrío), y el tratamiento se cumple completo, como lo indique el médico.</p>
      </div><div>
      <div class="qfig"><img class="tikz" src="paes/biologia/fig/evo_bacterias.svg" alt="Tres placas: población inicial con muchas bacterias sensibles azules y dos resistentes rojas; durante el tratamiento con antibiótico las sensibles mueren y las resistentes sobreviven; varias generaciones después toda la población es resistente"></div>
      <div class="box"><b>Recuerda</b> El antibiótico no crea la resistencia: selecciona a las bacterias que ya la tenían. La población cambia porque cambia la proporción de bacterias resistentes.</div>
      </div></div>` },
    { t: 'Lo clave del tema', b: r`
      <table><thead><tr><th>Concepto</th><th>Idea central</th><th>Ejemplo</th></tr></thead><tbody>
      <tr><td>Lamarck (1809)</td><td>uso y desuso; herencia de caracteres adquiridos</td><td>jirafa que estira el cuello</td></tr>
      <tr><td>Darwin y Wallace (1858-1859)</td><td>evolución por selección natural</td><td>pinzones, selección artificial</td></tr>
      <tr><td>Variación heredable</td><td>existe antes del cambio ambiental</td><td>polillas claras y oscuras</td></tr>
      <tr><td>Presión de selección</td><td>factor del ambiente que favorece a unas variantes</td><td>antibiótico, depredador, sequía</td></tr>
      <tr><td>Reproducción diferencial</td><td>los mejor adaptados dejan más descendencia</td><td>pinzones de pico profundo en la sequía</td></tr>
      <tr><td>Adaptación</td><td>rasgo heredable que aumenta la supervivencia o la reproducción</td><td>camuflaje, resistencia</td></tr></tbody></table>
      <div class="box" style="margin-top:14px"><b>Recuerda</b><br>· Los caracteres adquiridos durante la vida no se heredan.<br>· La variación surge al azar; el ambiente selecciona.<br>· Evoluciona la población, no el individuo.<br>· Ser adaptativo significa dejar más descendencia en ese ambiente.</div>
      <div class="box" style="margin-top:14px"><b>Método PAES</b> 1. Busca la variación previa en la población. 2. Identifica la presión de selección (qué cambió en el ambiente). 3. Pregunta qué variante sobrevive y se reproduce más. 4. Predice: esa variante aumenta su frecuencia a lo largo de generaciones. 5. Descarta las alternativas que dicen «para», «porque lo necesitaban» o «lo adquirieron y lo heredaron».</div>` }
  ],
  example: {
    src: 'Estilo PAES',
    enun: r`<p>En una isla vive una especie de ave que se alimenta de semillas; la profundidad del pico es una característica heredable. Durante una sequía de dos años, las plantas de semillas pequeñas y blandas casi desaparecieron, y quedaron sobre todo semillas grandes y duras, que solo las aves de pico profundo logran romper. El gráfico muestra la profundidad del pico en la población antes de la sequía y en la generación nacida después.</p><p>¿Qué explicación del cambio es coherente con la selección natural?</p>`,
    fig: { type: 'img', src: 'paes/biologia/fig/evo_pinzones.svg', alt: 'Gráfico de cantidad de aves según la profundidad del pico: la curva de antes de la sequía tiene su máximo en 9 mm y la de la generación siguiente está desplazada hacia la derecha, con máximo cerca de 9,8 mm' },
    alts: ['Al romper semillas duras, cada ave fortaleció y agrandó su pico, y heredó ese cambio a sus crías.', 'Las aves de pico más profundo sobrevivieron y se reprodujeron más durante la sequía, y sus crías heredaron esa característica.', 'La sequía causó mutaciones que hicieron crecer el pico de todas las aves de la isla.', 'Las aves necesitaban picos más grandes, por lo que sus crías nacieron con picos más profundos.'], ok: 1,
    sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Explicar con la selección natural por qué la curva se desplazó hacia picos más profundos.</p><p><b>Paso 2. Variación previa.</b> Antes de la sequía ya había aves con picos de distintas profundidades: la curva gris va de unos 7 a unos 11 mm.</p><p><b>Paso 3. Presión de selección.</b> La sequía dejó solo semillas grandes y duras. Las aves de pico profundo podían comerlas: sobrevivieron y se reprodujeron más que las de pico poco profundo.</p><p><b>Paso 4. Herencia.</b> Como la profundidad del pico es heredable, la generación siguiente tuvo más aves de pico profundo: la curva naranja está corrida hacia la derecha.</p><p><b>Respuesta:</b> las aves de pico más profundo sobrevivieron y se reprodujeron más, y sus crías heredaron esa característica.</p><p><b>¿Por qué no las otras?</b> Que el pico de cada ave cambie por el uso y ese cambio se herede es la explicación de Lamarck: un cambio adquirido durante la vida no se transmite. Las mutaciones ocurren al azar, no son causadas por la necesidad ni afectan a toda la población a la vez. «Necesitaban picos más grandes» también es lamarckista: la necesidad no produce la variación.</p>`,
    conc: 'El ambiente no cambia a los individuos: favorece a las variantes que ya existían, y la población cambia.'
  },
  bank: [
    /* Tipo 1: reconocer la idea de Lamarck, herencia de caracteres adquiridos (Invierno 2026 n.º 68 y 70) */
    { enun: r`<p>Un agricultor riega muy poco sus tomates durante toda la temporada, convencido de que así las plantas «se acostumbrarán» a la sequía. Luego guarda semillas de todas las plantas, sin elegir, y espera que la generación siguiente sea resistente a la falta de agua.</p><p>¿En qué idea evolutiva se basa el razonamiento del agricultor?</p>`, src: 'PAES Invierno 2026, adaptada',
      alts: ['En la selección natural.', 'En la herencia de los caracteres adquiridos.', 'En la variación por mutaciones al azar.', 'En la existencia de un ancestro común.'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> La idea que está detrás de esperar que un cambio logrado durante la vida pase a la descendencia.</p><p><b>Paso 2. Analiza el razonamiento.</b> El agricultor espera que las plantas adquieran tolerancia durante su vida y que la transmitan a sus semillas. Eso es la <b>herencia de los caracteres adquiridos</b>, propuesta por Lamarck.</p><p><b>Respuesta:</b> en la herencia de los caracteres adquiridos.</p><p><b>¿Por qué no las otras?</b> La selección natural requiere que sobrevivan y se reproduzcan más las plantas que ya eran tolerantes; el agricultor guarda semillas de todas, sin seleccionar. Las mutaciones al azar no dependen de la exposición a la sequía. El ancestro común explica el parentesco entre especies, no este procedimiento.</p>`, conc: 'Esperar que lo adquirido en la vida pase a las crías es la idea de Lamarck.' },
    { enun: r`<p>Algunas especies de peces que viven en cuevas sin luz tienen ojos muy reducidos o no los tienen, mientras que especies emparentadas que viven en ríos con luz tienen ojos funcionales.</p><p>¿Cuál de las siguientes explicaciones es lamarckista?</p>`, src: 'Estilo PAES',
      alts: ['En la población que colonizó la cueva había variación en el desarrollo de los ojos, y en la oscuridad tener ojos grandes no daba ventaja.', 'Las mutaciones que reducen los ojos aparecieron al azar y se mantuvieron en la población de la cueva.', 'Los peces con ojos reducidos dejaron más descendencia en la cueva, porque gastaban menos energía en formar ojos.', 'Como los peces dejaron de usar los ojos en la oscuridad, estos se atrofiaron en cada pez y ese cambio se heredó a sus crías.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Reconocer la explicación que corresponde a las ideas de Lamarck.</p><p><b>Paso 2. Busca las marcas de Lamarck.</b> Uso y desuso de un órgano durante la vida, y herencia de ese cambio. La última alternativa dice que los ojos se atrofiaron por no usarse y que ese cambio se heredó: es <b>lamarckista</b>.</p><p><b>Respuesta:</b> «como los peces dejaron de usar los ojos, estos se atrofiaron y ese cambio se heredó».</p><p><b>¿Por qué no las otras?</b> Las otras tres parten de variación previa o de mutaciones al azar, y de supervivencia o reproducción diferencial en la población: son explicaciones darwinistas, o de la teoría sintética.</p>`, conc: 'Uso y desuso más herencia de lo adquirido: explicación lamarckista.' },
    { enun: r`<p>Un investigador cortó la cola de ratones recién nacidos y, al llegar a adultos, los cruzó entre sí. Repitió el procedimiento con las crías durante varias generaciones y midió la cola de todos los ratones al nacer. Todos nacieron con cola de largo normal.</p><p>¿Qué hipótesis puso a prueba este experimento?</p>`, src: 'PAES Invierno 2026, adaptada',
      alts: ['Las características adquiridas durante la vida de un individuo se heredan a su descendencia.', 'El largo de la cola depende de la alimentación de los ratones.', 'La selección natural favorece a los ratones de cola larga.', 'Los ratones sin cola sobreviven más que los ratones con cola.'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> La hipótesis que se evalúa al cortar la cola en cada generación y medir la cola de las crías.</p><p><b>Paso 2. Identifica las variables.</b> Lo que se modifica es una característica adquirida durante la vida (la cola cortada). Lo que se mide es el largo de la cola de la descendencia. Se está probando si lo adquirido se hereda.</p><p><b>Paso 3. Lee el resultado.</b> Todas las crías nacieron con cola normal: la hipótesis queda refutada. La cola cortada no cambia el ADN de los gametos.</p><p><b>Respuesta:</b> que las características adquiridas durante la vida se heredan.</p><p><b>¿Por qué no las otras?</b> La alimentación no se varió. No hubo selección: todos los ratones se cruzaron y no se comparó cuántos sobrevivían o se reproducían. Tampoco se comparó la supervivencia de ratones con y sin cola.</p>`, conc: 'Lo que un individuo adquiere en su vida no cambia sus gametos: no se hereda.' },

    /* Tipo 2: fundamentos de la selección natural (Regular 2026 n.º 73, Invierno 2027 n.º 74) */
    { enun: r`<p>Junto a los relaves de una mina, el suelo tiene concentraciones de cobre tóxicas para la mayoría de las plantas de una especie de pasto. Después de muchas generaciones, la población que crece junto al relave está formada casi solo por plantas tolerantes al cobre.</p><p>¿Qué condición fue indispensable para que la selección natural produjera este resultado?</p>`, src: 'PAES Regular 2026, adaptada',
      alts: ['Que las plantas adquirieran tolerancia después de exponerse varias veces al cobre.', 'Que el cobre causara en cada planta las mutaciones que necesitaba.', 'Que en la población original hubiera plantas con distinta tolerancia al cobre y que esa diferencia fuera heredable.', 'Que todas las plantas de la población tuvieran la misma tolerancia al cobre.'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El requisito sin el cual la selección natural no puede actuar.</p><p><b>Paso 2. Recuerda los fundamentos.</b> La selección natural elige entre variantes que ya existen. Si en la población original había plantas más tolerantes y esa tolerancia se heredaba, esas plantas sobrevivieron y se reprodujeron más en el suelo con cobre, y su proporción aumentó.</p><p><b>Respuesta:</b> que hubiera variación heredable en la tolerancia al cobre.</p><p><b>¿Por qué no las otras?</b> Adquirir tolerancia por exposición y heredarla es una idea lamarckista. Las mutaciones aparecen al azar; el ambiente no las produce según lo que la planta necesita. Si todas las plantas fueran iguales, el cobre las afectaría a todas por igual y no habría nada que seleccionar.</p>`, conc: 'Sin variación heredable, la selección natural no tiene sobre qué actuar.' },
    { enun: r`<p>En una especie de ave, los machos con plumas de la cola más largas atraen a más hembras y logran aparearse más veces que los machos de cola corta. El largo de la cola es una característica heredable.</p><p>Según la teoría de Darwin y Wallace, ¿por qué la cola larga puede considerarse una característica adaptativa?</p>`, src: 'PAES Invierno 2027, adaptada',
      alts: ['Porque aumenta el éxito reproductivo de los machos que la presentan.', 'Porque las plumas crecen más cuando el macho las usa en el cortejo.', 'Porque aumenta la variabilidad genética de cada macho.', 'Porque les permite sobrevivir en ambientes fríos.'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Por qué un rasgo que atrae parejas es adaptativo.</p><p><b>Paso 2. Recuerda qué es adaptativo.</b> Una característica heredable es adaptativa si aumenta la supervivencia o la <b>reproducción</b>. Los machos de cola larga se aparean más veces: dejan más descendientes y transmiten el rasgo a más crías.</p><p><b>Respuesta:</b> porque aumenta el éxito reproductivo de los machos que la presentan.</p><p><b>¿Por qué no las otras?</b> Que las plumas crezcan por el uso sería un carácter adquirido, y además no es lo que describe el enunciado. La variabilidad genética es una propiedad de la población, no de un macho. El enunciado no relaciona la cola con el frío.</p>`, conc: 'Adaptativo = aumenta la supervivencia o la cantidad de descendencia.' },
    { enun: r`<p>Las siguientes afirmaciones describen el proceso de selección natural, en desorden:</p><p>1. Los individuos con la característica favorable sobreviven y se reproducen más.<br>2. En la población hay variación heredable en una característica.<br>3. A lo largo de las generaciones aumenta la frecuencia de la característica favorable.<br>4. Nacen más individuos de los que el ambiente puede sostener, y compiten por los recursos.</p><p>¿Cuál es el orden correcto?</p>`, src: 'Estilo PAES',
      alts: ['1, 4, 2, 3', '3, 2, 4, 1', '2, 3, 1, 4', '2, 4, 1, 3'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Ordenar los pasos de la selección natural.</p><p><b>Paso 2. Ordena.</b> Primero tiene que existir variación heredable (2). Como nacen más individuos de los que sobreviven, compiten (4). En esa competencia, los que tienen la característica favorable sobreviven y se reproducen más (1). Con las generaciones, esa característica se vuelve más frecuente (3).</p><p><b>Respuesta:</b> 2, 4, 1, 3.</p><p><b>¿Por qué no las otras?</b> «1, 4, 2, 3» pone la reproducción diferencial antes de que exista la variación sobre la que actúa. «3, 2, 4, 1» empieza por el resultado final. «2, 3, 1, 4» pone el aumento de frecuencia antes de la supervivencia diferencial que lo causa.</p>`, conc: 'Variación → competencia → supervivencia y reproducción diferencial → cambio en la población.' },
    { enun: r`<p>Un profesor pide a su curso elegir la afirmación correcta sobre la selección natural.</p><p>¿Cuál de las siguientes afirmaciones es correcta?</p>`, src: 'Estilo PAES',
      alts: ['Cada individuo cambia durante su vida para adaptarse al ambiente.', 'La selección natural produce las variaciones que la población necesita.', 'La selección natural actúa sobre los individuos, y el cambio en la frecuencia de las características se observa en la población.', 'Las características que un individuo adquiere por el uso se transmiten a su descendencia.'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> La única afirmación coherente con la teoría de la selección natural.</p><p><b>Paso 2. Recuerda quién cambia.</b> El ambiente favorece o perjudica a <b>individuos</b> según sus características; pero un individuo no cambia su ADN. Lo que cambia, a lo largo de generaciones, es la frecuencia de cada característica en la <b>población</b>.</p><p><b>Respuesta:</b> la selección actúa sobre los individuos y el cambio se observa en la población.</p><p><b>¿Por qué no las otras?</b> Los individuos no evolucionan durante su vida. La variación surge al azar por mutación y recombinación; la selección no la produce, solo actúa sobre ella. La herencia de caracteres adquiridos por el uso es la idea de Lamarck, que la evidencia descartó.</p>`, conc: 'Selección sobre individuos, evolución en la población.' },

    /* Tipo 3: ejemplos y predicciones con gráficos de frecuencia (Regular 2026 n.º 72) */
    { enun: r`<p>En una pradera vive una especie de saltamontes con individuos verdes y cafés; el color es heredable. Las aves que los cazan los buscan con la vista. Entre el año 2 y el año 8 hubo una sequía que secó el pasto, que pasó de verde a café. El gráfico muestra el porcentaje de cada color en la población.</p><p>¿Qué explica mejor el cambio observado?</p>`, src: 'PAES Regular 2026, adaptada',
      fig: { type: 'img', src: 'paes/biologia/fig/evo_saltamontes.svg', alt: 'Gráfico de barras: en el año 1 hay 80 % de saltamontes verdes y 20 % de cafés; en el año 8 hay 30 % de verdes y 70 % de cafés' },
      alts: ['Los saltamontes verdes cambiaron su color a café para camuflarse en el pasto seco.', 'Los saltamontes cafés eran menos visibles para las aves, sobrevivieron y se reprodujeron más, y su proporción aumentó.', 'La sequía provocó mutaciones que volvieron cafés a los saltamontes verdes.', 'Los saltamontes cafés depredaron a los verdes hasta reducir su número.'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Explicar por qué los cafés pasaron de 20 % a 70 % de la población.</p><p><b>Paso 2. Variación y presión de selección.</b> Ya en el año 1 había saltamontes cafés. Con el pasto seco, los cafés quedaron camuflados y los verdes, más visibles para las aves.</p><p><b>Paso 3. Reproducción diferencial.</b> Los cafés fueron menos cazados, sobrevivieron y dejaron más crías, que heredaron el color café. Generación tras generación, su proporción aumentó.</p><p><b>Respuesta:</b> los cafés eran menos visibles, sobrevivieron y se reprodujeron más.</p><p><b>¿Por qué no las otras?</b> Un saltamontes no cambia su color heredable «para» camuflarse: esa es una explicación lamarckista. La sequía no produce mutaciones dirigidas; los cafés ya existían antes. El enunciado indica que los depredadores son aves, no los propios saltamontes.</p>`, conc: 'El color que camufla en el nuevo ambiente aumenta su frecuencia.' },
    { enun: r`<p>En unas dunas de arena clara vive una población de ratones con pelaje claro y oscuro; el color del pelaje es heredable. Los ratones claros son menos cazados por búhos y halcones, porque se confunden con la arena. Después de una erupción volcánica, la zona queda cubierta durante décadas por arena volcánica oscura.</p><p>Si el color del pelaje está sujeto a selección natural, ¿qué es esperable que ocurra?</p>`, src: 'PAES Regular 2026, adaptada',
      alts: ['Los ratones claros oscurecerán su pelaje para camuflarse en la arena oscura.', 'Todos los ratones claros morirán en la primera generación.', 'La proporción de ratones claros y oscuros se mantendrá constante.', 'Con el paso de las generaciones, aumentará la proporción de ratones de pelaje oscuro.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Predecir el cambio en la población cuando cambia el color del suelo.</p><p><b>Paso 2. Nueva presión de selección.</b> Sobre arena oscura, ahora los ratones oscuros quedan camuflados y los claros resaltan frente a los depredadores.</p><p><b>Paso 3. Predice.</b> Los oscuros sobrevivirán y se reproducirán más, y sus crías heredarán el pelaje oscuro. Con las generaciones, su proporción aumentará.</p><p><b>Respuesta:</b> aumentará la proporción de ratones oscuros.</p><p><b>¿Por qué no las otras?</b> Un ratón no cambia su color heredable «para» camuflarse. La selección cambia proporciones de forma gradual; no elimina a todos los claros de inmediato. Si la proporción se mantuviera, el color no estaría sujeto a selección, lo que contradice el enunciado.</p>`, conc: 'Cambia el ambiente, cambia la variante favorecida y su frecuencia aumenta con las generaciones.' },
    { enun: r`<p>El gráfico muestra el porcentaje de polillas moteadas oscuras en una zona industrial de Inglaterra. En 1956 se aprobó una ley para reducir el humo de las fábricas; en las décadas siguientes, los troncos de los árboles se fueron limpiando y volvieron a cubrirse de líquenes claros.</p><p>¿Qué explica la disminución de las polillas oscuras después de 1965?</p>`, src: 'Estilo PAES',
      fig: { type: 'img', src: 'paes/biologia/fig/evo_polilla.svg', alt: 'Gráfico de porcentaje de polillas oscuras entre 1850 y 2000: sube de cerca de 2 % a 95 % hacia 1895, se mantiene alto hasta 1965 y baja a cerca de 10 % en 2000; una línea marca la ley de aire limpio de 1956' },
      alts: ['Sobre troncos claros, las polillas oscuras eran más visibles para las aves, y sobrevivieron y se reprodujeron menos que las claras.', 'Las polillas oscuras se aclararon al posarse sobre los troncos limpios.', 'El aire limpio provocó mutaciones que aclararon a las polillas.', 'Las polillas claras dejaron de ser cazadas por completo.'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Explicar la caída de las polillas oscuras, de cerca de 90 % a cerca de 10 %.</p><p><b>Paso 2. ¿Qué cambió en el ambiente?</b> Los troncos volvieron a ser claros. Ahora las polillas claras quedaban camufladas y las oscuras resaltaban.</p><p><b>Paso 3. Selección.</b> Las aves cazaron más polillas oscuras; las claras sobrevivieron y se reprodujeron más, y la proporción de oscuras bajó generación tras generación.</p><p><b>Respuesta:</b> sobre troncos claros, las oscuras eran más visibles y dejaron menos descendencia.</p><p><b>¿Por qué no las otras?</b> El color de una polilla es heredable y no cambia por posarse en un tronco. Las mutaciones no aparecen dirigidas por el ambiente. La depredación no tiene que desaparecer: basta con que las claras sean cazadas en menor proporción que las oscuras.</p>`, conc: 'La misma selección que favoreció a las oscuras favoreció después a las claras.' },
    { enun: r`<p>En las islas Galápagos viven varias especies de pinzones emparentadas, que descienden de un ancestro llegado desde el continente. Las especies se diferencian sobre todo en la forma del pico, relacionada con su alimento: semillas duras, insectos o flores de cactus.</p><p>¿Qué explicación de esta diversidad es coherente con la teoría de Darwin y Wallace?</p>`, src: 'Estilo PAES',
      alts: ['Cada pinzón modificó su pico según el alimento que usaba y transmitió ese cambio a sus crías.', 'Las especies llegaron a las islas desde distintos continentes, cada una con su pico ya formado.', 'En cada ambiente, la selección natural favoreció formas de pico distintas según el alimento disponible, y las poblaciones se fueron diferenciando.', 'Los pinzones necesitaban otro alimento, por lo que sus picos cambiaron en una sola generación.'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Explicar cómo, desde un ancestro común, surgieron especies con picos distintos.</p><p><b>Paso 2. Aplica la selección natural.</b> Las poblaciones que ocuparon distintas islas y ambientes tenían variación en el pico. En cada lugar sobrevivieron y se reprodujeron más las aves cuyo pico servía mejor para el alimento disponible. Con muchas generaciones, las poblaciones se diferenciaron hasta formar especies distintas.</p><p><b>Respuesta:</b> en cada ambiente, la selección natural favoreció picos distintos.</p><p><b>¿Por qué no las otras?</b> Modificar el pico por el uso y heredarlo es una idea lamarckista. El enunciado indica que descienden de un mismo ancestro, no de varios llegados por separado. La necesidad no produce cambios heredables, y la selección actúa a lo largo de muchas generaciones.</p>`, conc: 'Un ancestro común y ambientes distintos: la selección diversifica los picos.' },

    /* Tipo 4: resistencia a antibióticos y pesticidas (Regular 2026 n.º 14) */
    { enun: r`<p>La figura representa una población de bacterias antes, durante y varias generaciones después de un tratamiento con antibiótico.</p><p>¿Qué afirmación se apoya en el esquema?</p>`, src: 'PAES Regular 2026, adaptada',
      fig: { type: 'img', src: 'paes/biologia/fig/evo_bacterias.svg', alt: 'Tres placas: 1, población inicial con muchas bacterias sensibles y dos resistentes; 2, durante el tratamiento con antibiótico mueren las sensibles y sobreviven las dos resistentes; 3, varias generaciones después todas las bacterias son resistentes' },
      alts: ['El antibiótico provocó que algunas bacterias se volvieran resistentes.', 'Las bacterias resistentes ya estaban en la población antes de aplicar el antibiótico.', 'Después del tratamiento, la población es más variada en su resistencia que al inicio.', 'Las bacterias sensibles se transformaron en resistentes durante el tratamiento.'], ok: 1,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Una afirmación que se pueda leer directamente en las tres placas.</p><p><b>Paso 2. Mira la placa 1.</b> Antes del antibiótico ya hay dos bacterias rojas, resistentes.</p><p><b>Paso 3. Sigue el proceso.</b> En la placa 2 mueren las sensibles y sobreviven esas mismas dos. En la placa 3, sus descendientes forman toda la población.</p><p><b>Respuesta:</b> las bacterias resistentes ya estaban antes del antibiótico.</p><p><b>¿Por qué no las otras?</b> El antibiótico no creó la resistencia: las resistentes de la placa 2 son las mismas de la placa 1. Al final, todas son resistentes: la población es menos variada que al inicio. Las sensibles no se transformaron: murieron, como muestra el color gris.</p>`, conc: 'El antibiótico selecciona la resistencia que ya existía; no la crea.' },
    { enun: r`<p>Un equipo estudió dos poblaciones de una misma especie de insecto durante 12 generaciones: la población 1 se roció con un pesticida en cada generación y la población 2 no se roció. El gráfico muestra el porcentaje de insectos resistentes al pesticida en cada población.</p><p>¿Qué conclusión es correcta?</p>`, src: 'PAES Regular 2026, adaptada',
      fig: { type: 'img', src: 'paes/biologia/fig/evo_pesticida.svg', alt: 'Gráfico del porcentaje de insectos resistentes según la generación: la población 1, con pesticida, sube de 2 % a 94 % en 12 generaciones; la población 2, sin pesticida, se mantiene cerca de 2 %' },
      alts: ['El pesticida hizo que los insectos de la población 1 desarrollaran resistencia durante su vida.', 'En la población 2 no existen insectos resistentes.', 'Los insectos de la población 1 se volvieron resistentes porque lo necesitaban para sobrevivir.', 'El pesticida actuó como presión de selección y aumentó la proporción de insectos resistentes, que ya existían en baja proporción.'], ok: 3,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Interpretar las dos curvas.</p><p><b>Paso 2. Compara el inicio.</b> En la generación 0, ambas poblaciones tienen cerca de 2 % de insectos resistentes: la resistencia ya existía antes del pesticida.</p><p><b>Paso 3. Compara la tendencia.</b> Con pesticida, los resistentes suben hasta 94 %; sin pesticida, se mantienen cerca de 2 %. El pesticida elimina a los sensibles y los resistentes dejan más descendencia: es una presión de selección.</p><p><b>Respuesta:</b> el pesticida actuó como presión de selección sobre una resistencia que ya existía.</p><p><b>¿Por qué no las otras?</b> La resistencia no se desarrolla durante la vida de cada insecto: estaba presente desde la generación 0. En la población 2 sí hay resistentes, alrededor de 2 %. La necesidad no produce cambios heredables.</p>`, conc: 'El pesticida no crea resistentes: aumenta su proporción al eliminar a los sensibles.' },
    { enun: r`<p>Un hongo ataca los cultivos de uva. En un laboratorio se mantuvieron cultivos del hongo a la misma temperatura y humedad, expuestos a cuatro fungicidas distintos, y cada semana se registró su respuesta:</p><table><thead><tr><th>Semana</th><th>Fungicida 1</th><th>Fungicida 2</th><th>Fungicida 3</th><th>Fungicida 4</th></tr></thead><tbody><tr><td>0</td><td>−</td><td>−</td><td>−</td><td>−</td></tr><tr><td>4</td><td>−</td><td>+</td><td>−</td><td>−</td></tr><tr><td>8</td><td>−</td><td>+</td><td>−</td><td>+</td></tr><tr><td>12</td><td>+</td><td>+</td><td>−</td><td>+</td></tr><tr><td>16</td><td>+</td><td>+</td><td>+</td><td>+</td></tr></tbody></table><p>+ = resistencia al fungicida; − = sensibilidad al fungicida.</p><p>¿Qué pregunta de investigación pudo guiar este estudio?</p>`, src: 'PAES Regular 2026, adaptada',
      alts: ['¿Cuánto tiempo de exposición transcurre hasta que el hongo presenta resistencia a cada fungicida?', '¿Qué mutación le permite al hongo resistir a los fungicidas?', '¿Cómo influye la humedad en la resistencia del hongo a los fungicidas?', '¿Qué fungicida es menos tóxico para las plantas de uva?'], ok: 0,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> Una pregunta que se responda con los datos de la tabla.</p><p><b>Paso 2. Lee las variables.</b> Se varió el fungicida y se registró, semana a semana, si el hongo era sensible o resistente. La tabla muestra <b>cuándo aparece la resistencia</b> a cada fungicida: semana 4 para el 2, semana 8 para el 4, semana 12 para el 1 y semana 16 para el 3.</p><p><b>Respuesta:</b> ¿cuánto tiempo de exposición transcurre hasta que el hongo presenta resistencia a cada fungicida?</p><p><b>¿Por qué no las otras?</b> La tabla no informa ningún dato genético, así que no permite identificar mutaciones. La humedad se mantuvo constante: no se puede estudiar su efecto. En el estudio no hay plantas de uva, por lo que no se midió la toxicidad para ellas.</p>`, conc: 'La pregunta de investigación relaciona exactamente lo que se varió con lo que se midió.' },
    { enun: r`<p>Las autoridades de salud recomiendan no usar antibióticos para tratar resfríos, que son causados por virus, y usarlos solo con receta médica.</p><p>¿Por qué el uso innecesario de antibióticos favorece el aumento de bacterias resistentes?</p>`, src: 'Estilo PAES',
      alts: ['Porque las bacterias que reciben el antibiótico se acostumbran a él y heredan esa costumbre.', 'Porque los antibióticos transforman a los virus en bacterias resistentes.', 'Porque cada uso del antibiótico elimina bacterias sensibles y deja más espacio y recursos para que las resistentes se multipliquen.', 'Porque la persona se vuelve inmune al antibiótico.'], ok: 2,
      sol: r`<p><b>Paso 1. ¿Qué nos piden?</b> El mecanismo por el que el mal uso de antibióticos aumenta la resistencia.</p><p><b>Paso 2. Aplica la selección natural.</b> En el cuerpo hay muchas bacterias, y algunas son resistentes. Cada vez que se usa un antibiótico, mueren las sensibles y sobreviven las resistentes, que se multiplican con menos competencia. El antibiótico actúa como presión de selección, aunque la enfermedad sea viral.</p><p><b>Respuesta:</b> cada uso elimina bacterias sensibles y favorece la multiplicación de las resistentes.</p><p><b>¿Por qué no las otras?</b> «Acostumbrarse» y heredarlo es una idea lamarckista. Los antibióticos no actúan sobre los virus ni los transforman en bacterias. La resistencia es una característica de las bacterias, no de la persona.</p>`, conc: 'Cada uso de antibiótico es una presión de selección a favor de las bacterias resistentes.' }
  ]
}

];
